name: Bulk disable workflows
on:
  workflow_dispatch:
    inputs:
      keep_list:
        description: "Pliki workflow (po przecinku), które mają pozostać aktywne"
        required: false
        default: "pipeline-deploy-wpcli.yml,ssot-guard.yml"

permissions:
  contents: write

jobs:
  disable:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Zbuduj whitelistę
        id: keep
        run: |
          set -euo pipefail
          IFS=',' read -r -a ARR <<< "${{ github.event.inputs.keep_list }}"
          norm=""
          for x in "${ARR[@]}"; do
            x="$(echo "$x" | xargs)"
            x="$(basename "$x")"
            [ -n "$x" ] && norm="${norm}${x}\n"
          done
          mkdir -p .github/workflows
          printf "%b" "$norm" | sort -u > .github/workflows/.keep_list
          echo "WHITELIST:"
          cat .github/workflows/.keep_list

      - name: Przenazwij inne workflowy na .disabled
        run: |
          set -euo pipefail
          cd .github/workflows

          # wczytaj whitelistę do tablicy
          mapfile -t KEEP < .keep_list || true

          shopt -s nullglob
          ALL=( *.yml *.yaml )
          CHANGED=0

          for f in "${ALL[@]}"; do
            # jeśli plik sam jest tym bulk-* → zostaw zawsze
            [[ "$f" == bulk-disable-workflows.yml || "$f" == bulk-enable-workflows.yml ]] && { echo "KEEP  : $f (bulk tool)"; continue; }

            # jeśli na liście keep → zostaw
            SKIP=false
            for k in "${KEEP[@]}"; do
              [[ "$f" == "$k" ]] && { SKIP=true; break; }
            done
            $SKIP && { echo "KEEP  : $f"; continue; }

            # jeśli już wyłączony → pomiń
            [[ "$f" == *.disabled ]] && { echo "DISABLED already: $f"; continue; }

            mv "$f" "$f.disabled"
            echo "DISABLE -> $f.disabled"
            CHANGED=1
          done

          echo "CHANGED=$CHANGED" >> $GITHUB_ENV

      - name: Commit i push
        if: env.CHANGED == '1'
        run: |
          set -euo pipefail
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .github/workflows
          git commit -m "chore: bulk disable workflows (keep whitelist)"
          git push

      - name: Brak zmian
        if: env.CHANGED != '1'
        run: echo "Nie było nic do wyłączenia."
