name: WP-CLI plugins debug & install

on:
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  debug:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    env:
      HOST:   ${{ secrets.DEPLOY_HOST }}
      PORT:   ${{ secrets.DEPLOY_PORT }}
      USER:   ${{ secrets.DEPLOY_USER }}
      PASS:   ${{ secrets.DEPLOY_PASS }}
      TARGET: ${{ secrets.DEPLOY_TARGET }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Verify secrets & allowlist exists locally
        shell: bash
        run: |
          set -euo pipefail
          test -n "${HOST:-}" && test -n "${PORT:-}" && test -n "${USER:-}" && test -n "${PASS:-}" && test -n "${TARGET:-}" || { echo "::error::Missing deploy secrets"; exit 1; }
          test -f ".wtp/allowed-plugins.txt" || { echo "::error::.wtp/allowed-plugins.txt not found"; exit 1; }
          echo "Local allowlist:"
          nl -ba .wtp/allowed-plugins.txt

      - name: Upload allowlist
        shell: bash
        run: |
          set -euo pipefail
          sshpass -p "$PASS" scp -P "$PORT" -o StrictHostKeyChecking=no \
            ".wtp/allowed-plugins.txt" "$USER@$HOST:$TARGET/.wtp-allowed-plugins.txt"

      - name: Ensure WP-CLI on remote
        shell: bash
        run: |
          set -euo pipefail
          sshpass -p "$PASS" ssh -p "$PORT" -o StrictHostKeyChecking=no "$USER@$HOST" '
            set -e
            cd "$TARGET"
            if ! command -v wp >/dev/null 2>&1; then
              echo "[remote] installing wp-cli..."
              curl -sS -o wp.phar https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
              php wp.phar --info >/dev/null
              chmod +x wp.phar && mv wp.phar wp
            fi
            echo "[remote] wp-cli ok"
          '

      - name: Probe WordPress context & print server allowlist
        id: probe
        shell: bash
        run: |
          set -euo pipefail
          sshpass -p "$PASS" ssh -p "$PORT" -o StrictHostKeyChecking=no "$USER@$HOST" '
            set -e
            cd "$TARGET"
            echo "----- server allowlist (cat -A) -----"
            cat -A ".wtp-allowed-plugins.txt" || true
            echo "----- wp core version -----"
            php ./wp core version || { echo "::error::wp core not accessible in $TARGET"; exit 1; }
            echo "----- current plugin list (before) -----"
            php ./wp plugin list || true
          '

      - name: Install/update plugins from allowlist (verbose)
        shell: bash
        run: |
          set -euo pipefail
          sshpass -p "$PASS" ssh -p "$PORT" -o StrictHostKeyChecking=no "$USER@$HOST" '
            set -e
            cd "$TARGET"
            REPORT=".wtp/reports/wpcli-install-${GITHUB_RUN_ID}.md"
            mkdir -p .wtp/reports
            echo "# WP-CLI install from allowlist – run ${GITHUB_RUN_ID}" > "$REPORT"
            echo "" >> "$REPORT"
            echo "```" >> "$REPORT"
            nl -ba ".wtp-allowed-plugins.txt" >> "$REPORT"
            echo "```" >> "$REPORT"
            echo "" >> "$REPORT"

            # normalize & loop
            sed -e "s/\r\$//" ".wtp-allowed-plugins.txt" | sed "s/^\xEF\xBB\xBF//" | while IFS= read -r line; do
              line="${line%%#*}"; line="$(echo "$line" | xargs)"
              [ -z "$line" ] && continue
              slug="${line%@*}"
              ver=""
              if echo "$line" | grep -q "@"; then ver="${line#*@}"; fi

              if [ -n "$ver" ]; then
                echo ">> INSTALL $slug@$ver" | tee -a "$REPORT"
                set +e
                php ./wp --debug plugin install "$slug" --version="$ver" --force --activate 2>&1 | tee -a "$REPORT"
                rc=${PIPESTATUS[0]}
                set -e
              else
                echo ">> INSTALL/UPDATE $slug (latest)" | tee -a "$REPORT"
                if php ./wp plugin is-installed "$slug" >/dev/null 2>&1; then
                  set +e
                  php ./wp --debug plugin update "$slug" --activate 2>&1 | tee -a "$REPORT"
                  rc=${PIPESTATUS[0]}
                  set -e
                else
                  set +e
                  php ./wp --debug plugin install "$slug" --activate 2>&1 | tee -a "$REPORT"
                  rc=${PIPESTATUS[0]}
                  set -e
                fi
              fi
              if [ $rc -ne 0 ]; then
                echo "::warning::wp-cli failed for $slug (rc=$rc)"
                echo "!! rc=$rc" >> "$REPORT"
              fi
              echo "" >> "$REPORT"
            done

            echo "----- plugin list (after) -----" >> "$REPORT"
            php ./wp plugin list >> "$REPORT" || true
          '

      - name: Commit report
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "ci: wp-cli plugins debug report #${{ github.run_id }}"
          file_pattern: ".wtp/reports/wpcli-install-*.md"
          branch: main
