name: 03_snapshot_full (server state → repo SSOT, safe wp-config)

on:
  workflow_dispatch: {}
  workflow_run:
    workflows: ["02_wpcli (install/update/activate from SSOT, secure SSH)"]
    types: [completed]

permissions:
  contents: write

concurrency:
  group: snapshot_full
  cancel-in-progress: true

jobs:
  snapshot_full:
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    timeout-minutes: 30

    env:
      HOST:   ${{ secrets.DEPLOY_HOST }}
      PORT:   ${{ secrets.DEPLOY_PORT }}
      USER:   ${{ secrets.DEPLOY_USER }}
      PASS:   ${{ secrets.DEPLOY_PASS }}
      TARGET: ${{ secrets.DEPLOY_TARGET }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup tools (sshpass, yq, jq, curl)
        run: |
          set -euo pipefail
          sudo apt-get update -y
          sudo apt-get install -y sshpass curl jq
          curl -sSL https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -o yq
          chmod +x yq && sudo mv yq /usr/local/bin/yq

          mkdir -p ~/.ssh && chmod 700 ~/.ssh
          ssh-keyscan -p "$PORT" "$HOST" >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts
          echo "::add-mask::$HOST"
          echo "::add-mask::$USER"

      - name: Pull snapshot from server
        run: |
          set -euo pipefail
          sshpass -p "$PASS" ssh -p "$PORT" \
            -o StrictHostKeyChecking=yes \
            -o UserKnownHostsFile=~/.ssh/known_hosts \
            "$USER@$HOST" "cd '$TARGET' && bash .wtp/scripts/snapshot_full.sh" || true

          mkdir -p _ci_logs/${{ github.run_id }}/snapshot_full
          sshpass -p "$PASS" scp -P "$PORT" -r \
            -o StrictHostKeyChecking=yes -o UserKnownHostsFile=~/.ssh/known_hosts \
            "$USER@$HOST:$TARGET/.wtp/state/ro/public/latest/*" \
            "_ci_logs/${{ github.run_id }}/snapshot_full/" || true

      - name: Render safe wp-config.php.head.txt (dummy only)
        run: |
          set -euo pipefail
          RAW="_ci_logs/${{ github.run_id }}/snapshot_full"
          mkdir -p "${RAW}"
          test -f ".wtp/templates/wp-config.dummy.php" || { echo "::error::Missing .wtp/templates/wp-config.dummy.php"; exit 1; }
          cp ".wtp/templates/wp-config.dummy.php" "${RAW}/wp-config.php.head.txt"
          sed -i 's/${WP_DB_NAME}/db_name/g; s/${WP_DB_USER}/db_user/g; s/${WP_DB_PASSWORD}/***REDACTED***/g; s/${WP_DB_HOST}/db_host/g; s#${WP_HOME_URL}#https://weektoppick.com#g; s#${WP_SITEURL}#https://weektoppick.com#g' "${RAW}/wp-config.php.head.txt"

      - name: Scrub secrets from all pulled logs
        run: |
          set -euo pipefail
          ROOT="_ci_logs/${{ github.run_id }}/snapshot_full"
          [ -d "$ROOT" ] || exit 0

          # GitHub tokens
          grep -RIl --null -e 'ghp_' -e 'github_pat_' -e 'gho_' "$ROOT" | \
            xargs -0 -I{} sed -i -E 's/(ghp_[A-Za-z0-9]{20,})/***REDACTED***/g; s/(github_pat_[A-Za-z0-9_]{20,})/***REDACTED***/g; s/(gho_[A-Za-z0-9]{20,})/***REDACTED***/g' {} || true
          # Authorization headers
          grep -RIl --null -e 'Authorization:' -e 'Bearer ' "$ROOT" | \
            xargs -0 -I{} sed -i -E 's/(Authorization:\s*Bearer\s+)[A-Za-z0-9\.\-_]+/\1***REDACTED***/g' {} || true
          # WP salts
          grep -RIl --null -e 'AUTH_KEY' -e 'SECURE_AUTH_KEY' -e 'LOGGED_IN_KEY' -e 'NONCE_KEY' -e 'AUTH_SALT' -e 'SECURE_AUTH_SALT' -e 'LOGGED_IN_SALT' -e 'NONCE_SALT' "$ROOT" | \
            xargs -0 -I{} sed -i -E 's/(define\(.+,\s*).+(\)\s*;)/\1"***REDACTED***"\2/g' {} || true

          # FAIL SAFE
          if grep -RIl -e 'ghp_' -e 'github_pat_' -e 'Authorization:' "$ROOT" >/dev/null 2>&1; then
            echo "::error::Potential secret left after scrub. Aborting push."
            exit 2
          fi

      - name: Commit & push snapshot
        run: |
          set -euo pipefail
          DEST=".wtp/state/ro/public/latest"
          mkdir -p "$DEST"
          cp -r _ci_logs/${{ github.run_id }}/snapshot_full/* "$DEST/" || true
          git config user.name "wtp-ci"
          git config user.email "wtp-ci@users.noreply.github.com"
          git add "$DEST"
          git commit -m "[ci] snapshot_full: refresh state (safe wp-config)" || exit 0
          git push
