name: 97_theme_fix_functions
on:
  workflow_dispatch: {}

permissions:
  contents: read

concurrency:
  group: fix-functions
  cancel-in-progress: true

jobs:
  fix:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      HOST:   ${{ secrets.DEPLOY_HOST }}
      PORT:   ${{ secrets.DEPLOY_PORT }}
      USER:   ${{ secrets.DEPLOY_USER }}
      PASS:   ${{ secrets.DEPLOY_PASS }}
      TARGET: ${{ secrets.DEPLOY_TARGET }}

    steps:
      - name: Patch functions.php (ensure valid PHP open tags) + lint
        uses: appleboy/ssh-action@v1.0.3
        with:
          host:     ${{ env.HOST }}
          username: ${{ env.USER }}
          password: ${{ env.PASS }}
          port:     ${{ env.PORT }}
          envs: TARGET
          script: |
            set -euo pipefail
            TARGET="${TARGET:-$HOME/domains/weektoppick.com/public_html}"
            cd "$TARGET"

            FILE="wp-content/themes/wtp-core-theme/functions.php"
            if [ ! -f "$FILE" ]; then
              echo "::error file not found::$FILE"
              exit 1
            fi

            # backup
            cp -a "$FILE" "${FILE}.bak.$(date -u +%Y%m%d%H%M%S)"

            # PHP one-liner: do 2 rzeczy
            # 1) jeżeli plik nie zaczyna się od <?php — dopisz
            # 2) zamień " ?php" (bez '<') na "<?php"
            php -r '
              $f = "wp-content/themes/wtp-core-theme/functions.php";
              $s = file_get_contents($f);
              if ($s === false) { fwrite(STDERR, "read failed\n"); exit(2); }
              if (strncmp($s, "<?php", 5) !== 0) { $s = "<?php\n" . $s; }
              $s = preg_replace("/(?<!<)\\?php/", "<?php", $s);
              file_put_contents($f, $s);
            '

            # lint – jeżeli błąd, wyjdź
            php -l "$FILE"

            # pokaż nagłówek pliku dla kontroli
            head -n 40 "$FILE" || true

            # purge cache jeśli Litespeed aktywny
            if command -v wp >/dev/null 2>&1; then
              wp plugin is-active litespeed-cache && wp litespeed-purge all || true
            fi
