name: Remote inventory (plugins & themes)

on:
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  inventory:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      HOST:   ${{ secrets.DEPLOY_HOST }}
      PORT:   ${{ secrets.DEPLOY_PORT }}
      USER:   ${{ secrets.DEPLOY_USER }}
      PASS:   ${{ secrets.DEPLOY_PASS }}
      TARGET: ${{ secrets.DEPLOY_TARGET }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Collect inventory via WP-CLI (php ./wp)
        shell: bash
        run: |
          set -euo pipefail
          sshpass -p "$PASS" ssh -p "$PORT" -o StrictHostKeyChecking=no "$USER@$HOST" "set -e
            cd \"$TARGET\"
            php -v >/dev/null 2>&1 || { echo '::error::php cli not available'; exit 1; }
            [ -f ./wp ] || { echo '::error::wp-cli (./wp) missing'; exit 1; }
            WP='php ./wp'
            mkdir -p .wtp-state
            \$WP plugin list --format=json > .wtp-state/plugins.json
            \$WP theme  list --format=json > .wtp-state/themes.json
          "

      - name: Pull inventory to repo and commit
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p .wtp/state/inventory
          sshpass -p "$PASS" scp -P "$PORT" -o StrictHostKeyChecking=no \
            "$USER@$HOST:$TARGET/.wtp-state/plugins.json" ".wtp/state/inventory/plugins.json"
          sshpass -p "$PASS" scp -P "$PORT" -o StrictHostKeyChecking=no \
            "$USER@$HOST:$TARGET/.wtp-state/themes.json"  ".wtp/state/inventory/themes.json"

      - name: Commit inventory
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "ci: update remote inventory (plugins/themes)"
          file_pattern: ".wtp/state/inventory/*.json"
          branch: main
