name: 00_maintenance_runner

on:
  workflow_dispatch:
    inputs:
      workflow_file:
        description: "Plik z .github/workflows._maintenance/, np. 03_repo_audit.yml"
        required: true
      keep_active:
        description: "Zostawić plik aktywny po odpaleniu? (yes/no)"
        required: false
        default: "no"

permissions:
  contents: write
  actions: write   # wymagane do API: workflow dispatch

concurrency:
  group: maintenance-runner
  cancel-in-progress: true

jobs:
  run_maintenance:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Validate & paths
        id: val
        run: |
          set -euo pipefail
          WF_M_DIR=".github/workflows._maintenance"
          WF_DIR=".github/workflows"
          NAME="${{ github.event.inputs.workflow_file }}"
          test -n "$NAME" || { echo "::error::Empty workflow_file"; exit 1; }
          test -f "${WF_M_DIR}/${NAME}" || { echo "::error::Brak ${WF_M_DIR}/${NAME}"; exit 1; }
          echo "src=${WF_M_DIR}/${NAME}" >> "$GITHUB_OUTPUT"
          echo "dst=${WF_DIR}/${NAME}" >> "$GITHUB_OUTPUT"

      - name: Move to active
        run: |
          set -euo pipefail
          src="${{ steps.val.outputs.src }}"
          dst="${{ steps.val.outputs.dst }}"
          mkdir -p "$(dirname "$dst")"
          mv -f "$src" "$dst"
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add "$dst"
          git commit -m "maintenance-runner: activate $(basename "$dst") temporarily" || true
          git push || true
          sleep 3

      - name: Trigger via GitHub API
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          BRANCH: ${{ github.ref_name }}
          WF_FILE: ${{ github.event.inputs.workflow_file }}
        run: |
          set -euo pipefail
          RESP=$(mktemp)
          CODE=$(curl -sS -w "%{http_code}" -o "$RESP" -X POST \
            -H "Authorization: Bearer $GH_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            "https://api.github.com/repos/${REPO}/actions/workflows/${WF_FILE}/dispatches" \
            -d "{\"ref\":\"${BRANCH}\"}")
          echo "HTTP $CODE"; cat "$RESP" || true
          if [ "$CODE" -ne 204 ]; then
            echo "::error::Workflow dispatch failed (HTTP $CODE)"; exit 1
          fi
          echo "::notice::Triggered ${WF_FILE} on ${BRANCH}"

      - name: Move back to _maintenance (unless keep_active=yes)
        if: ${{ github.event.inputs.keep_active != 'yes' }}
        run: |
          set -euo pipefail
          WF_DIR=".github/workflows"
          WF_M_DIR=".github/workflows._maintenance"
          NAME="${{ github.event.inputs.workflow_file }}"
          if [ -f "${WF_DIR}/${NAME}" ]; then
            mv -f "${WF_DIR}/${NAME}" "${WF_M_DIR}/${NAME}"
            git config user.name  "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add "${WF_M_DIR}/${NAME}" "${WF_DIR}" || true
            git commit -m "maintenance-runner: move back ${NAME} to _maintenance" || true
            git push || true
          fi

      - name: Done
        run: echo "::notice::Launched ${{ github.event.inputs.workflow_file }} (check Actions list)"
