name: 00_recover_layout

on:
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: recover-layout
  cancel-in-progress: true

jobs:
  recover:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Restore maintenance workflows to active & retire launcher
        shell: bash
        run: |
          set -euo pipefail

          WF_DIR=".github/workflows"
          WF_M_DIR=".github/workflows._maintenance"
          WF_Q_DIR=".github/workflows._quarantine"
          mkdir -p "$WF_DIR" "$WF_M_DIR" "$WF_Q_DIR"

          moved_any=0

          echo "== Move ALL maintenance workflows to active =="
          shopt -s nullglob
          for p in "$WF_M_DIR"/*.yml "$WF_M_DIR"/*.yaml; do
            [[ -e "$p" ]] || continue
            b="$(basename "$p")"
            if [[ -f "$WF_DIR/$b" ]]; then
              echo "skip (exists in active): $b"
              continue
            fi
            echo "move: $p -> $WF_DIR/$b"
            git mv -f "$p" "$WF_DIR/$b"
            moved_any=1
          done
          shopt -u nullglob

          echo "== Retire launcher (00_maintenance_tasks.yml) =="
          LAUNCH_SRC="$WF_DIR/00_maintenance_tasks.yml"
          LAUNCH_DST="$WF_M_DIR/00_maintenance_tasks.yml.disabled"
          if [[ -f "$LAUNCH_SRC" ]]; then
            echo "move: $LAUNCH_SRC -> $LAUNCH_DST"
            git mv -f "$LAUNCH_SRC" "$LAUNCH_DST"
            moved_any=1
          else
            echo "launcher not present in active (ok)."
          fi

          if [[ ! -f "$WF_M_DIR/README.md" ]]; then
            cat > "$WF_M_DIR/README.md" << 'MD'
# Workflows – maintenance
Ten katalog przechowuje *wyłączone* lub *okazjonalne* workflowy.
`00_maintenance_tasks.yml` został wyłączony (sufiks `.disabled`), żeby nie mieszać listy Actions.
Przywracanie: przenieś z powrotem do `.github/workflows/` i usuń `.disabled`.
MD
            git add "$WF_M_DIR/README.md"
          fi

          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          if [[ "$moved_any" -eq 1 ]]; then
            git add -A
            git commit -m "recover-layout: move maintenance → active, retire launcher" || true
            git pull --rebase --autostash origin "${GITHUB_REF_NAME:-main}" || true
            git push || true
          else
            echo "::notice::Nothing to change."
          fi

      - name: Summary
        if: always()
        run: |
          echo "::notice::Gotowe. Wejdź w Actions – wszystkie maintenance wróciły do listy. Launcher wyłączony."
