name: 00_ssh_check (SSH key smoke)

on:
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  ssh-check:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4

      - name: Setup SSH key & known_hosts
        env:
          HOST:   ${{ secrets.DEPLOY_HOST }}
          PORT:   ${{ secrets.DEPLOY_PORT }}
          USER:   ${{ secrets.DEPLOY_USER }}
          TARGET: ${{ secrets.DEPLOY_TARGET }}
          SSHKEY: ${{ secrets.DEPLOY_SSH_KEY }}
        run: |
          set -euo pipefail
          for v in HOST PORT USER TARGET SSHKEY; do
            [ -n "${!v:-}" ] || { echo "::error::Missing $v"; exit 1; }
          done
          mkdir -p ~/.ssh && chmod 700 ~/.ssh
          printf "%s" "$SSHKEY" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -p "$PORT" "$HOST" >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts
          echo "env-ok"

      - name: SSH smoke (read-only)
        env:
          HOST:   ${{ secrets.DEPLOY_HOST }}
          PORT:   ${{ secrets.DEPLOY_PORT }}
          USER:   ${{ secrets.DEPLOY_USER }}
          TARGET: ${{ secrets.DEPLOY_TARGET }}
        run: |
          set -euo pipefail
          ssh -p "$PORT" -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=yes "$USER@$HOST" "bash -lc '
            whoami; hostname; pwd;
            cd \"$TARGET\" || { echo \"ERR: cannot cd to TARGET\"; exit 2; }
            test -f wp-config.php && echo OK:wp-config || { echo ERR:no-wp-config; exit 3; }
            ls -la | head -n 20
          '"
