name: 00_workflow_lint

on:
  push:
    paths:
      - ".github/workflows/*.yml"
  pull_request:
    paths:
      - ".github/workflows/*.yml"
  workflow_dispatch: {}

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run actionlint
        uses: rhysd/actionlint@v1
