name: 02_wpcli (install/update/activate from SSOT, secure SSH)

on:
  workflow_dispatch: {}
  workflow_run:
    workflows: ["01_deploy (single-run, password auth, strict host key, rsync, sanity)"]
    types: [completed]

permissions:
  contents: read

concurrency:
  group: wpcli
  cancel-in-progress: true

jobs:
  wpcli:
    # Run only when 01_deploy succeeded, or when triggered manually
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    timeout-minutes: 30

    env:
      HOST:   ${{ secrets.DEPLOY_HOST }}
      PORT:   ${{ secrets.DEPLOY_PORT }}
      USER:   ${{ secrets.DEPLOY_USER }}
      PASS:   ${{ secrets.DEPLOY_PASS }}
      TARGET: ${{ secrets.DEPLOY_TARGET }}
      WTP_CI: "1"   # bypass LOCKS via MU-plugin

    steps:
      - uses: actions/checkout@v4

      - name: Preflight (tools + known_hosts)
        run: |
          set -euo pipefail
          for v in HOST PORT USER PASS TARGET; do
            [ -n "${!v:-}" ] || { echo "::error::Missing $v"; exit 1; }
          done
          sudo apt-get update -y
          sudo apt-get install -y curl sshpass
          curl -sSL https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -o yq
          chmod +x yq && sudo mv yq /usr/local/bin/yq
          mkdir -p ~/.ssh && chmod 700 ~/.ssh
          ssh-keyscan -p "$PORT" "$HOST" >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts
          echo "::add-mask::$HOST"
          echo "::add-mask::$USER"

      - name: Build plugin list from SSOT
        run: |
          set -euo pipefail
          if [ ! -f ".wtp/ssot.yml" ]; then
            echo "::warning::.wtp/ssot.yml missing – empty plugin list"
            : > .wtp/plugins.install.list
          else
            yq -e '.plugins.install // []' .wtp/ssot.yml >/dev/null
            yq -r '.plugins.install // [] | .[]' .wtp/ssot.yml > .wtp/plugins.install.list || true
          fi
          echo "---- plugins.install ----"
          cat .wtp/plugins.install.list || true

      - name: Create remote sanity script
        run: |
          set -euo pipefail
          cat > /tmp/sanity_script.sh <<'SCRIPT'
          set -euo pipefail
          cd "$TARGET" || { echo "::error::Cannot cd to TARGET"; exit 1; }
          php -v >/dev/null 2>&1 || { echo "::error::php CLI not available"; exit 1; }
          if [ ! -x ./wp ]; then
            curl -sS -L -o wp.phar https://github.com/wp-cli/wp-cli/releases/latest/download/wp-cli.phar
            php wp.phar --info >/dev/null 2>&1
            chmod +x wp.phar && mv wp.phar wp
          fi
          mkdir -p .wtp/state/ci_logs
          : > .wtp/state/ci_logs/wpcli_summary.txt
          SCRIPT

      - name: Remote sanity and install wp-cli (local)
        run: |
          set -euo pipefail
          sshpass -p "$PASS" scp -P "$PORT" \
            -o StrictHostKeyChecking=yes -o UserKnownHostsFile=~/.ssh/known_hosts \
            "/tmp/sanity_script.sh" "$USER@$HOST:$TARGET/.tmp_sane.sh"
          sshpass -p "$PASS" ssh -p "$PORT" \
            -o StrictHostKeyChecking=yes -o UserKnownHostsFile=~/.ssh/known_hosts \
            "$USER@$HOST" "TARGET='$TARGET' bash '$TARGET/.tmp_sane.sh' && rm -f '$TARGET/.tmp_sane.sh'"

      - name: Ensure remote .wtp and upload plugin list
        run: |
          set -euo pipefail
          sshpass -p "$PASS" ssh -p "$PORT" \
            -o StrictHostKeyChecking=yes -o UserKnownHostsFile=~/.ssh/known_hosts \
            "$USER@$HOST" "mkdir -p '$TARGET/.wtp'"
          if [ -s ".wtp/plugins.install.list" ]; then
            sshpass -p "$PASS" scp -P "$PORT" \
              -o StrictHostKeyChecking=yes -o UserKnownHostsFile=~/.ssh/known_hosts \
              ".wtp/plugins.install.list" "$USER@$HOST:$TARGET/.wtp/plugins.install.list"
          else
            echo "(empty plugin list)"
          fi

      - name: Create remote plugins script
        run: |
          set -euo pipefail
          cat > /tmp/plugins_script.sh <<'SCRIPT'
          set -euo pipefail
          cd "$TARGET"
          export WP_ALLOW_ROOT=1
          export WTP_CI=1

          mkdir -p .wtp/state/ci_logs
          : > .wtp/state/ci_logs/plugins_installed.txt
          : > .wtp/state/ci_logs/plugins_updated.txt
          : > .wtp/state/ci_logs/plugins_existing.txt
          : > .wtp/state/ci_logs/errors.txt
          : > .wtp/state/ci_logs/active_plugins.csv
          : > .wtp/state/ci_logs/wpcli_raw.log
          : > .wtp/state/ci_logs/wpcli_summary.txt

          echo "=== PLUGINS INPUT LIST ===" | tee -a .wtp/state/ci_logs/wpcli_summary.txt
          if [ -s .wtp/plugins.install.list ]; then
            cat .wtp/plugins.install.list | tee -a .wtp/state/ci_logs/wpcli_summary.txt
          else
            echo "(empty)" | tee -a .wtp/state/ci_logs/wpcli_summary.txt
          fi

          echo "=== ACTIVE PLUGINS (before) ===" | tee -a .wtp/state/ci_logs/wpcli_summary.txt
          php ./wp plugin list --format=csv --path="$TARGET" --skip-plugins 2>> .wtp/state/ci_logs/wpcli_raw.log \
            | tee .wtp/state/ci_logs/active_plugins.csv | tee -a .wtp/state/ci_logs/wpcli_summary.txt >/dev/null \
            || echo "active-dump-fail:plugin-list-csv" >> .wtp/state/ci_logs/errors.txt

          install_force () {
            slug="$1"; ver="${2:-}"
            if [ -n "$ver" ]; then
              php ./wp --debug plugin install "$slug" --version="$ver" --force --path="$TARGET" --skip-plugins 2>&1 | tee -a .wtp/state/ci_logs/wpcli_raw.log
            else
              php ./wp --debug plugin install "$slug" --force --path="$TARGET" --skip-plugins 2>&1 | tee -a .wtp/state/ci_logs/wpcli_raw.log
            fi
            return ${PIPESTATUS[0]}
          }
          install_zip_force () {
            slug="$1"; zip="/tmp/${slug}.zip"; url="https://downloads.wordpress.org/plugin/${slug}.latest-stable.zip"
            curl -fL -o "$zip" "$url" 2>> .wtp/state/ci_logs/wpcli_raw.log || return 1
            php ./wp --debug plugin install "$zip" --force --path="$TARGET" --skip-plugins 2>&1 | tee -a .wtp/state/ci_logs/wpcli_raw.log
            return ${PIPESTATUS[0]}
          }

          if [ ! -s .wtp/plugins.install.list ]; then
            echo "No plugins to process (empty list)" | tee -a .wtp/state/ci_logs/wpcli_summary.txt
            exit 0
          fi

          while IFS= read -r raw; do
            line="$(echo "$raw" | sed 's/#.*$//' | xargs)"; [ -z "$line" ] && continue
            slug="$line"; ver=""
            if printf "%s" "$line" | grep -q "@"; then slug="${line%@*}"; ver="${line##*@}"; fi

            if php ./wp plugin is-installed "$slug" --path="$TARGET" --skip-plugins; then
              echo "$slug" >> .wtp/state/ci_logs/plugins_existing.txt
              if [ -n "$ver" ]; then
                php ./wp --debug plugin update "$slug" --version="$ver" --path="$TARGET" --skip-plugins 2>&1 | tee -a .wtp/state/ci_logs/wpcli_raw.log \
                  && echo "updated:$slug@$ver" >> .wtp/state/ci_logs/plugins_updated.txt \
                  || echo "update-fail:$slug@$ver" >> .wtp/state/ci_logs/errors.txt
              else
                php ./wp --debug plugin update "$slug" --path="$TARGET" --skip-plugins 2>&1 | tee -a .wtp/state/ci_logs/wpcli_raw.log \
                  && echo "updated:$slug" >> .wtp/state/ci_logs/plugins_updated.txt \
                  || echo "update-fail:$slug" >> .wtp/state/ci_logs/errors.txt
              fi
            else
              installed=false
              if install_force "$slug" "$ver"; then
                echo "$slug${ver:+@$ver}" >> .wtp/state/ci_logs/plugins_installed.txt
                installed=true
              else
                if install_zip_force "$slug"; then
                  echo "$slug" >> .wtp/state/ci_logs/plugins_installed.txt
                  installed=true
                fi
              fi
              [ "$installed" = true ] || echo "install-fail:$slug${ver:+@$ver}" >> .wtp/state/ci_logs/errors.txt
            fi

            php ./wp --debug plugin activate "$slug" --path="$TARGET" --skip-plugins 2>&1 | tee -a .wtp/state/ci_logs/wpcli_raw.log \
              || echo "activate-fail:$slug" >> .wtp/state/ci_logs/errors.txt
          done < .wtp/plugins.install.list

          echo "=== ACTIVE PLUGINS (after) ===" | tee -a .wtp/state/ci_logs/wpcli_summary.txt
          php ./wp plugin list --format=csv --path="$TARGET" --skip-plugins | tee .wtp/state/ci_logs/active_plugins.csv | tee -a .wtp/state/ci_logs/wpcli_summary.txt >/dev/null \
            || echo "active-dump-fail:active-csv" >> .wtp/state/ci_logs/errors.txt
          php ./wp plugin list --status=active --field=name --path="$TARGET" --skip-plugins > .wtp/state/ci_logs/plugins_active.txt \
            || echo "active-dump-fail:active-field" >> .wtp/state/ci_logs/errors.txt
          SCRIPT

      - name: Execute remote plugins script
        run: |
          set -euo pipefail
          sshpass -p "$PASS" scp -P "$PORT" \
            -o StrictHostKeyChecking=yes -o UserKnownHostsFile=~/.ssh/known_hosts \
            "/tmp/plugins_script.sh" "$USER@$HOST:$TARGET/.tmp_plugins.sh"
          sshpass -p "$PASS" ssh -p "$PORT" \
            -o StrictHostKeyChecking=yes -o UserKnownHostsFile=~/.ssh/known_hosts \
            "$USER@$HOST" "TARGET='$TARGET' bash '$TARGET/.tmp_plugins.sh' && rm -f '$TARGET/.tmp_plugins.sh'"

      - name: Pull logs back (artifact)
        run: |
          set -euo pipefail
          mkdir -p "_ci_logs/${{ github.run_id }}/wpcli"
          sshpass -p "$PASS" scp -P "$PORT" -r \
            -o StrictHostKeyChecking=yes -o UserKnownHostsFile=~/.ssh/known_hosts \
            "$USER@$HOST:$TARGET/.wtp/state/ci_logs/*" "_ci_logs/${{ github.run_id }}/wpcli/" || true
          ls -la "_ci_logs/${{ github.run_id }}/wpcli" || true

      - name: Upload artifact (wpcli logs)
        uses: actions/upload-artifact@v4
        with:
          name: wpcli-logs-${{ github.run_id }}
          path: _ci_logs/${{ github.run_id }}/wpcli/**
          retention-days: 14

      - name: Report errors if any (notice/warn)
        run: |
          set -euo pipefail
          ERR="_ci_logs/${{ github.run_id }}/wpcli/errors.txt"
          if [ -f "$ERR" ] && [ -s "$ERR" ]; then
            echo "::group::WP-CLI errors"
            cat "$ERR" || true
            echo "::endgroup::"
            echo "::warning::Some plugins failed. See errors.txt above."
          else
            echo "::notice::WP-CLI operations completed successfully"
          fi
