name: 03_snapshot_full (server state → repo SSOT, safe wp-config with PR fallback)

on:
  workflow_dispatch: {}
  workflow_run:
    workflows: ["02_wpcli (install/update/activate from SSOT, secure SSH)"]
    types: [completed]

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: snapshot_full
  cancel-in-progress: true

jobs:
  snapshot_full:
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    timeout-minutes: 30

    env:
      HOST:   ${{ secrets.DEPLOY_HOST }}
      PORT:   ${{ secrets.DEPLOY_PORT }}
      USER:   ${{ secrets.DEPLOY_USER }}
      PASS:   ${{ secrets.DEPLOY_PASS }}
      TARGET: ${{ secrets.DEPLOY_TARGET }}
      RUN_ID: ${{ github.run_id }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup tools
        run: |
          set -euo pipefail
          sudo apt-get update -y
          sudo apt-get install -y sshpass curl jq
          curl -sSL https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -o yq
          chmod +x yq && sudo mv yq /usr/local/bin/yq
          mkdir -p ~/.ssh && chmod 700 ~/.ssh
          ssh-keyscan -p "$PORT" "$HOST" >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - name: (Remote) build snapshot
        run: |
          set -euo pipefail
          sshpass -p "$PASS" ssh -p "$PORT" \
            -o StrictHostKeyChecking=yes \
            -o UserKnownHostsFile=~/.ssh/known_hosts \
            "$USER@$HOST" "cd '$TARGET' && [ -x .wtp/scripts/snapshot_full.sh ] && bash .wtp/scripts/snapshot_full.sh || true"

      - name: Pull snapshot files
        run: |
          set -euo pipefail
          mkdir -p "_ci_logs/${RUN_ID}/snapshot_full"
          sshpass -p "$PASS" scp -P "$PORT" -r \
            -o StrictHostKeyChecking=yes -o UserKnownHostsFile=~/.ssh/known_hosts \
            "$USER@$HOST:$TARGET/.wtp/state/ro/public/latest/*" \
            "_ci_logs/${RUN_ID}/snapshot_full/" || true

      - name: Render safe wp-config.php.head.txt
        run: |
          RAW="_ci_logs/${RUN_ID}/snapshot_full"
          mkdir -p "$RAW"
          if [ -f ".wtp/templates/wp-config.dummy.php" ]; then
            cp ".wtp/templates/wp-config.dummy.php" "$RAW/wp-config.php.head.txt"
            sed -i \
              -e 's/${WP_DB_NAME}/db_name/g' \
              -e 's/${WP_DB_USER}/db_user/g' \
              -e 's/${WP_DB_PASSWORD}/***REDACTED***/g' \
              -e 's/${WP_DB_HOST}/db_host/g' \
              -e 's#${WP_HOME_URL}#https://weektoppick.com#g' \
              -e 's#${WP_SITEURL}#https://weektoppick.com#g' \
              "$RAW/wp-config.php.head.txt"
          fi

      - name: Scrub secrets (fail-safe)
        run: |
          ROOT="_ci_logs/${RUN_ID}/snapshot_full"
          [ -d "$ROOT" ] || exit 0
          # GITHUB tokens
          grep -RIl --null -e 'ghp_' -e 'github_pat_' -e 'gho_' "$ROOT" | \
            xargs -0 -I{} sed -i -E 's/(ghp_[A-Za-z0-9]{20,})/***REDACTED***/g; s/(github_pat_[A-Za-z0-9_]{20,})/***REDACTED***/g; s/(gho_[A-Za-z0-9]{20,})/***REDACTED***/g' {} || true
          # WP salts
          grep -RIl --null -e 'AUTH_KEY' -e 'NONCE_KEY' -e 'AUTH_SALT' -e 'NONCE_SALT' "$ROOT" | \
            xargs -0 -I{} sed -i -E 's/(define\(.+,\s*).+(\)\s*;)/\1"***REDACTED***"\2/g' {} || true
          # Final check
          if grep -RIl -e 'ghp_' -e 'github_pat_' -e 'gho_' "$ROOT"; then
            echo "::error::Secrets still present, aborting push"
            exit 2
          fi

      - name: Stage snapshot
        run: |
          DEST=".wtp/state/ro/public/latest"
          mkdir -p "$DEST"
          cp -r "_ci_logs/${RUN_ID}/snapshot_full/." "$DEST/"

      - name: Commit
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add ".wtp/state/ro/public/latest"
          git commit -m "[ci] snapshot_full ${RUN_ID}" || echo "nothing to commit"

      - name: Push to main
        id: pushmain
        continue-on-error: true
        run: git push origin HEAD:main

      - name: Fallback PR
        if: steps.pushmain.outcome != 'success'
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "[ci] snapshot_full ${RUN_ID}"
          title: "Snapshot FULL ${RUN_ID}"
          body: "Main push blocked, opening PR with sanitized snapshot"
          branch: ci/snapshot-${{ env.RUN_ID }}
          delete-branch: true
          labels: ci,snapshot
