name: 94_collect_errors

on:
  workflow_dispatch: {}

permissions:
  contents: write

concurrency:
  group: collect-errors
  cancel-in-progress: true

jobs:
  collect:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      HOST:   ${{ secrets.DEPLOY_HOST }}
      PORT:   ${{ secrets.DEPLOY_PORT }}
      USER:   ${{ secrets.DEPLOY_USER }}
      PASS:   ${{ secrets.DEPLOY_PASS }}
      TARGET: ${{ secrets.DEPLOY_TARGET }}
      RUN_ID: ${{ github.run_id }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup tools
        run: |
          set -euo pipefail
          sudo apt-get update -y
          sudo apt-get install -y sshpass

      - name: Collect errors & admin status
        run: |
          set -euo pipefail
          mkdir -p "_ci_logs/${RUN_ID}"
          REMOTE_DIR="${TARGET:-$HOME/domains/weektoppick.com/public_html}"
          OUT="${REMOTE_DIR}/.wtp/state/ci_logs/collect_errors"
          mkdir -p "${OUT}"

          cd "${REMOTE_DIR}" || exit 0

          # active theme
          if command -v wp >/dev/null 2>&1; then
            wp theme list --status=active --field=name 2>/dev/null | head -n1 > "${OUT}/active_theme.txt" || true
          else
            : > "${OUT}/active_theme.txt"
          fi

          # admin status
          if command -v wp >/dev/null 2>&1; then
            wp user list --role=administrator --field=user_login --format=json 2>/dev/null > "${OUT}/status_admin.txt" || echo "[]" > "${OUT}/status_admin.txt"
          else
            echo "[]" > "${OUT}/status_admin.txt"
          fi

          # collect logs
          for LOG in error_log logs/error_log wp-content/debug.log; do
            [ -f "$LOG" ] && tail -n 200 "$LOG" > "${OUT}/$(echo "$LOG" | tr '/' '_')" || true
          done

          # stderr during WP bootstrap
          php -r 'require "wp-load.php";' 2> "${OUT}/wp_boot_stderr.txt" || true

          echo "[INFO] errors collected into ${OUT}"

      - name: Pull collected errors
        run: |
          set -euo pipefail
          mkdir -p "_ci_logs/${RUN_ID}"
          REMOTE_DIR="${TARGET:-$HOME/domains/weektoppick.com/public_html}/.wtp/state/ci_logs/collect_errors"

          sshpass -p "${PASS}" scp -P "${PORT}" -o StrictHostKeyChecking=no -r \
            "${USER}@${HOST}:${REMOTE_DIR}" "_ci_logs/${RUN_ID}/" || {
              echo "::error::no errors pulled"
              exit 2
          }

          ls -la "_ci_logs/${RUN_ID}/collect_errors" || true

      - name: Commit & push errors
        run: |
          set -euo pipefail
          RO_DIR=".wtp/state/ro/public/latest/collect-errors"
          mkdir -p "${RO_DIR}"
          cp -a "_ci_logs/${RUN_ID}/collect_errors/." "${RO_DIR}/"

          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          if git diff --staged --quiet; then
            echo "::notice::Nothing to commit."; exit 0
          fi
          git commit -m "[ci] collected errors (run ${RUN_ID})"
          git push origin HEAD:${GITHUB_REF_NAME:-main}
