name: 95_admin_unbrick
on: workflow_dispatch

jobs:
  fix:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      HOST:   ${{ secrets.DEPLOY_HOST }}
      PORT:   ${{ secrets.DEPLOY_PORT }}
      USER:   ${{ secrets.DEPLOY_USER }}
      PASS:   ${{ secrets.DEPLOY_PASS }}
      TARGET: ${{ secrets.DEPLOY_TARGET }}

    steps:
      - name: SSH: TT25 + MU OFF + plugins OFF + purge + ping
        uses: appleboy/ssh-action@v1.0.3
        with:
          host:     ${{ env.HOST }}
          username: ${{ env.USER }}
          password: ${{ env.PASS }}
          port:     ${{ env.PORT }}
          envs: TARGET
          script: |
            set -euo pipefail
            TARGET="${TARGET:-$HOME/domains/weektoppick.com/public_html}"
            cd "$TARGET" || exit 1
            rm -f .maintenance || true

            # MU-plugins OFF (wszystkie)
            if [ -d wp-content/mu-plugins ]; then
              for f in wp-content/mu-plugins/*.php; do
                [ -f "$f" ] && mv -f "$f" "$f.off" || true
              done
            fi

            # Plugins OFF + przełącz na Twenty Twenty-Five + purge LS
            if command -v wp >/dev/null 2>&1; then
              wp plugin deactivate --all --quiet || true
              wp theme install twentytwentyfive --activate --force || wp theme activate twentytwentyfive || true
              wp plugin is-active litespeed-cache && wp litespeed-purge all || true
            fi

            # Ping frontu (log)
            HOMEURL="$(php -r 'include "wp-config.php"; include "wp-load.php"; echo get_option("home");' 2>/dev/null || echo https://weektoppick.com)"
            curl -ks -o /dev/null -w "STATUS:%{http_code}\n" "$HOMEURL" || true

            echo "[DONE] admin unbrick complete"
