name: 96_nuke_wtp_theme

on:
  workflow_dispatch: {}

permissions:
  contents: write

concurrency:
  group: hotfix-nuke-theme
  cancel-in-progress: true

jobs:
  nuke:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      HOST:   ${{ secrets.DEPLOY_HOST }}
      PORT:   ${{ secrets.DEPLOY_PORT }}
      USER:   ${{ secrets.DEPLOY_USER }}
      PASS:   ${{ secrets.DEPLOY_PASS }}
      TARGET: ${{ secrets.DEPLOY_TARGET }}
      RUN_ID: ${{ github.run_id }}

    steps:
      - uses: actions/checkout@v4

      - name: SSH nuke wtp-core-theme
        uses: appleboy/ssh-action@v1.0.3
        with:
          host:     ${{ env.HOST }}
          username: ${{ env.USER }}
          password: ${{ env.PASS }}
          port:     ${{ env.PORT }}
          envs:     TARGET
          script: |
            set -euo pipefail
            TARGET="${TARGET:-$HOME/domains/weektoppick.com/public_html}"
            echo "[INFO] TARGET=$TARGET"
            cd "$TARGET"

            rm -f .maintenance || true

            # usuń wadliwy motyw
            if [ -d "wp-content/themes/wtp-core-theme" ]; then
              echo "[WARN] Removing broken theme wtp-core-theme"
              rm -rf wp-content/themes/wtp-core-theme
            fi

            if command -v wp >/dev/null 2>&1; then
              echo "[INFO] Switching to twentytwentyfive"
              wp theme install twentytwentyfive --activate --force || wp theme activate twentytwentyfive || true
              wp plugin is-active litespeed-cache && wp litespeed-purge all || true
            else
              echo "[WARN] wp-cli not found, theme switch skipped"
            fi

            echo "[DONE] wtp-core-theme removed and site rolled back"
