name: 96_emergency_heal

on:
  workflow_dispatch: {}

permissions:
  contents: write

concurrency:
  group: emergency-heal
  cancel-in-progress: true

jobs:
  heal:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    env:
      HOST: ${{ secrets.DEPLOY_HOST }}
      PORT: ${{ secrets.DEPLOY_PORT }}
      USER: ${{ secrets.DEPLOY_USER }}
      PASS: ${{ secrets.DEPLOY_PASS }}
      TARGET: ${{ secrets.DEPLOY_TARGET }}
      RUN_ID: ${{ github.run_id }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup tools
        run: |
          set -euo pipefail
          sudo apt-get update -y
          sudo apt-get install -y sshpass

      - name: Create theme files locally
        run: |
          mkdir -p /tmp/wtp-theme
          echo '/*' > /tmp/wtp-theme/style.css
          echo ' Theme Name: WTP Core Theme' >> /tmp/wtp-theme/style.css
          echo ' Description: Emergency theme' >> /tmp/wtp-theme/style.css
          echo ' Version: 1.0' >> /tmp/wtp-theme/style.css
          echo '*/' >> /tmp/wtp-theme/style.css
          
          echo '<?php' > /tmp/wtp-theme/functions.php
          echo 'add_theme_support("title-tag");' >> /tmp/wtp-theme/functions.php
          echo 'add_theme_support("post-thumbnails");' >> /tmp/wtp-theme/functions.php
          
          echo '<!doctype html>' > /tmp/wtp-theme/header.php
          echo '<html><head><meta charset="utf-8"><title>Emergency</title></head><body>' >> /tmp/wtp-theme/header.php
          
          echo '</body></html>' > /tmp/wtp-theme/footer.php
          
          echo '<?php get_header(); ?>' > /tmp/wtp-theme/index.php
          echo '<main><h1>Emergency Mode Active</h1></main>' >> /tmp/wtp-theme/index.php
          echo '<?php get_footer(); ?>' >> /tmp/wtp-theme/index.php

      - name: Emergency heal via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ env.HOST }}
          username: ${{ env.USER }}
          password: ${{ env.PASS }}
          port: ${{ env.PORT }}
          request_pty: true
          envs: TARGET,RUN_ID
          script: |
            set -euo pipefail
            cd "${TARGET:-$HOME/public_html}"
            
            mkdir -p .wtp/state/ci_logs/emergency_heal_${RUN_ID}
            OUT=".wtp/state/ci_logs/emergency_heal_${RUN_ID}"
            
            rm -f .maintenance
            echo "Emergency heal started" > "$OUT/status.txt"
            
            if [ -d wp-content/mu-plugins ]; then
              find wp-content/mu-plugins -name "*.php" -not -name "00-*" -not -name "mu-hotfix-*" -exec mv {} {}.off \;
            fi
            
            if command -v wp; then
              wp plugin deactivate --all --quiet || true
            fi
            
            mkdir -p wp-content/themes/wtp-emergency
            echo "Emergency theme created" >> "$OUT/status.txt"

      - name: Upload theme files
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ env.HOST }}
          username: ${{ env.USER }}
          password: ${{ env.PASS }}
          port: ${{ env.PORT }}
          source: /tmp/wtp-theme/*
          target: ${{ env.TARGET }}/wp-content/themes/wtp-emergency/
          strip_components: 2

      - name: Activate emergency theme
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ env.HOST }}
          username: ${{ env.USER }}
          password: ${{ env.PASS }}
          port: ${{ env.PORT }}
          request_pty: true
          envs: TARGET,RUN_ID
          script: |
            cd "${TARGET:-$HOME/public_html}"
            
            if command -v wp; then
              wp theme activate wtp-emergency || true
            fi
            
            echo "Emergency heal completed" >> .wtp/state/ci_logs/emergency_heal_${RUN_ID}/status.txt

      - name: Pull report
        if: always()
        run: |
          set -euo pipefail
          mkdir -p "_ci_logs/${RUN_ID}/emergency_heal"
          
          sshpass -p "${PASS}" scp -P "${PORT}" -o StrictHostKeyChecking=no -r \
            "${USER}@${HOST}:${TARGET}/.wtp/state/ci_logs/emergency_heal_${RUN_ID}/*" \
            "_ci_logs/${RUN_ID}/emergency_heal/" || true
          
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A || true
          git commit -m "Emergency heal report ${RUN_ID}" || true
          git push || true
