name: 97_theme_fix_functions
on:
  workflow_dispatch: {}
permissions:
  contents: write
concurrency:
  group: theme-fix-functions
  cancel-in-progress: true

jobs:
  fix:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      HOST:   ${{ secrets.DEPLOY_HOST }}
      PORT:   ${{ secrets.DEPLOY_PORT }}
      USER:   ${{ secrets.DEPLOY_USER }}
      PASS:   ${{ secrets.DEPLOY_PASS }}
      TARGET: ${{ secrets.DEPLOY_TARGET }}
      RUN_ID: ${{ github.run_id }}

    steps:
      - uses: actions/checkout@v4

      - name: Replace functions.php with safe stub
        uses: appleboy/ssh-action@v1.0.3
        with:
          host:     ${{ env.HOST }}
          username: ${{ env.USER }}
          password: ${{ env.PASS }}
          port:     ${{ env.PORT }}
          envs: TARGET,RUN_ID
          script: |
            set -euo pipefail
            TARGET="${TARGET:-$HOME/domains/weektoppick.com/public_html}"
            cd "$TARGET"

            THEME_DIR="wp-content/themes/wtp-core-theme"
            FILE="$THEME_DIR/functions.php"
            OUT="$TARGET/.wtp/state/ci_logs/theme_fix_${RUN_ID}"
            mkdir -p "$OUT" "$THEME_DIR"

            # backup jeśli istnieje
            if [ -f "$FILE" ]; then
              cp -f "$FILE" "$OUT/functions.php.bak" || true
            fi

            # bezpieczny stub (brak short open tags, tylko PHP)
            cat > "$FILE" <<'PHP'
<?php
/**
 * Safe stub functions.php for wtp-core-theme.
 * Keeps site alive while we iterate.
 */
if (!defined('ABSPATH')) { exit; }

/** Basic theme supports */
add_action('after_setup_theme', function () {
    add_theme_support('title-tag');
    add_theme_support('post-thumbnails');
});

/** No-op placeholders to avoid fatal errors if called elsewhere */
if (!function_exists('wtp_bootstrap')) {
    function wtp_bootstrap() { return true; }
}
PHP

            # szybka walidacja składni
            php -l "$FILE" || { echo "[ERR] PHP lint failed"; exit 3; }

            echo "[OK] functions.php replaced with safe stub" | tee "$OUT/action.txt"

      - name: Purge caches (best effort)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host:     ${{ env.HOST }}
          username: ${{ env.USER }}
          password: ${{ env.PASS }}
          port:     ${{ env.PORT }}
          envs: TARGET
          script: |
            set -euo pipefail
            TARGET="${TARGET:-$HOME/domains/weektoppick.com/public_html}"
            cd "$TARGET"
            if command -v wp >/dev/null 2>&1; then
              wp plugin is-active litespeed-cache >/dev/null 2>&1 && wp litespeed-purge all || true
            fi
            echo "[OK] purge attempted"
