name: 98_seed_minimal_theme

on:
  workflow_dispatch: {}

permissions:
  contents: write

concurrency:
  group: seed-minimal-theme
  cancel-in-progress: true

jobs:
  seed:
    runs-on: ubuntu-latest
    timeout-minutes: 12
    env:
      HOST:   ${{ secrets.DEPLOY_HOST }}
      PORT:   ${{ secrets.DEPLOY_PORT }}
      USER:   ${{ secrets.DEPLOY_USER }}
      PASS:   ${{ secrets.DEPLOY_PASS }}
      TARGET: ${{ secrets.DEPLOY_TARGET }}
      RUN_ID: ${{ github.run_id }}

    steps:
      - uses: actions/checkout@v4

      - name: Seed minimal wtp-core-theme + promote safely
        uses: appleboy/ssh-action@v1.0.3
        with:
          host:     ${{ env.HOST }}
          username: ${{ env.USER }}
          password: ${{ env.PASS }}
          port:     ${{ env.PORT }}
          envs: TARGET,RUN_ID
          script: |
            set -euo pipefail
            TARGET="${TARGET:-$HOME/domains/weektoppick.com/public_html}"
            cd "${TARGET}" || { echo "[ERR] no TARGET ${TARGET}"; exit 2; }

            THEME_DIR="wp-content/themes/wtp-core-theme"
            OUT="${TARGET}/.wtp/state/ci_logs/try-theme_${RUN_ID}"
            mkdir -p "${OUT}"

            rm -f .maintenance || true

            # 0) Home URL
            HOMEURL="$(php -r 'if(file_exists("wp-config.php")){ include "wp-config.php"; @include "wp-load.php"; if(function_exists("get_option")){ echo get_option("home"); }}' 2>/dev/null || true)"
            HOMEURL="${HOMEURL:-https://weektoppick.com}"
            echo "$HOMEURL" > "${OUT}/home_url.txt"

            # 1) Zapisz aktywny motyw "przed"
            (command -v wp >/dev/null 2>&1 && wp theme list --status=active --field=name 2>/dev/null | head -n1) > "${OUT}/theme_before.txt" || true

            # 2) Zasiej minimalny motyw (czyści katalog jeśli istnieje)
            rm -rf "$THEME_DIR"
            mkdir -p "$THEME_DIR"

            cat > "$THEME_DIR/style.css" <<'CSS'
            /*
            Theme Name: WTP Core Theme
            Theme URI: https://weektoppick.com
            Author: WeekTopPick
            Author URI: https://weektoppick.com
            Description: Minimal seed theme for WTP (safe)
            Version: 0.0.1
            Text Domain: wtp-core-theme
            */
            CSS

            cat > "$THEME_DIR/functions.php" <<'PHP'
            <?php
            // Safe minimal bootstrap — no output/echo here.
            add_action('after_setup_theme', function () {
              add_theme_support('title-tag');
              add_theme_support('post-thumbnails');
              add_theme_support('html5', ['search-form','comment-form','comment-list','gallery','caption','style','script']);
            });

            add_action('wp_enqueue_scripts', function () {
              // Load a very small inline CSS to prove render
              $css = "body{font-family:system-ui,-apple-system,Segoe UI,Roboto,Ubuntu; margin:0; padding:0;} .wtp-hello{padding:24px;max-width:840px;margin:40px auto;border:1px solid #ddd;border-radius:8px}";
              wp_register_style('wtp-core-inline', false);
              wp_enqueue_style('wtp-core-inline');
              wp_add_inline_style('wtp-core-inline', $css);
            });
            PHP

            cat > "$THEME_DIR/header.php" <<'PHP'
            <?php
            ?><!doctype html>
            <html <?php language_attributes(); ?>>
            <head>
              <meta charset="<?php bloginfo('charset'); ?>" />
              <meta name="viewport" content="width=device-width, initial-scale=1" />
              <?php wp_head(); ?>
            </head>
            <body <?php body_class(); ?>>
            <header class="wtp-header" role="banner"></header>
            <main role="main">
            PHP

            cat > "$THEME_DIR/footer.php" <<'PHP'
            </main>
            <footer class="wtp-footer" role="contentinfo"></footer>
            <?php wp_footer(); ?>
            </body></html>
            PHP

            cat > "$THEME_DIR/index.php" <<'PHP'
            <?php get_header(); ?>
            <div class="wtp-hello">
              <h1>WeekTopPick — seed theme OK</h1>
              <p>Jeśli to czytasz, motyw działa. Teraz będziemy iterować layout/i18n/kategorie.</p>
            </div>
            <?php if (have_posts()): while (have_posts()): the_post(); ?>
              <article id="post-<?php the_ID(); ?>" <?php post_class(); ?>>
                <h2><a href="<?php the_permalink(); ?>"><?php the_title(); ?></a></h2>
                <div><?php the_excerpt(); ?></div>
              </article>
            <?php endwhile; endif; ?>
            <?php get_footer(); ?>
            PHP

            # 3) Aktywuj i sprawdź zdrowie
            if command -v wp >/dev/null 2>&1; then
              ACT_RC=0
              wp theme activate wtp-core-theme || ACT_RC=$?
              echo "$ACT_RC" > "${OUT}/activate_rc.txt"
            else
              echo "wp-cli missing" > "${OUT}/activate_rc.txt"
            fi

            STATUS=$(curl -ks -o /dev/null -w "%{http_code}" "$HOMEURL" || echo 000)
            BODY="$(curl -ks "$HOMEURL" || true)"
            echo "$STATUS" > "${OUT}/http_status_after.txt"
            printf "%s" "$BODY" > "${OUT}/home_after.html"
            echo "$(printf "%s" "$BODY" | wc -c)" > "${OUT}/home_after_size.txt"

            # 4) Logi
            for LOG in error_log logs/error_log wp-content/debug.log; do
              [ -f "$LOG" ] && tail -n 200 "$LOG" > "${OUT}/$(echo "$LOG" | tr '/' '_')" || true
            done

            # 5) Rollback jeśli niezdrowo
            SIZE=$(cat "${OUT}/home_after_size.txt" || echo 0)
            if [ "$STATUS" != "200" ] || [ "${SIZE:-0}" -lt 600 ]; then
              echo "[WARN] unhealthy after promote (status=$STATUS size=$SIZE) -> rollback" | tee "${OUT}/action.txt"
              if command -v wp >/dev/null 2>&1; then
                wp theme install twentytwentyfive --activate --force || wp theme activate twentytwentyfive || true
                wp plugin is-active litespeed-cache >/dev/null 2>&1 && wp litespeed-purge all || true
              fi
            else
              echo "[OK] wtp-core-theme healthy (status=$STATUS size=$SIZE)" | tee "${OUT}/action.txt"
            fi

            # 6) zapis "po"
            (command -v wp >/dev/null 2>&1 && wp theme list --status=active --field=name 2>/dev/null | head -n1) > "${OUT}/theme_after.txt" || true

      - name: Pull logs to latest/try-theme
        run: |
          set -euo pipefail
          mkdir -p "_ci_logs/${RUN_ID}/try-theme"
          sshpass -p "${PASS}" scp -P "${PORT}" -o StrictHostKeyChecking=no -r \
            "${USER}@${HOST}:${TARGET}/.wtp/state/ci_logs/try-theme_${RUN_ID}/." \
            "_ci_logs/${RUN_ID}/try-theme/" || { echo "::error::no try-theme logs pulled"; exit 2; }

          RO_DIR=".wtp/state/ro/public/${RUN_ID}/try-theme"
          RO_LATEST=".wtp/state/ro/public/latest/try-theme"
          mkdir -p "${RO_DIR}" "${RO_LATEST}"
          cp -a "_ci_logs/${RUN_ID}/try-theme/." "${RO_DIR}/"
          rm -rf "${RO_LATEST}"; mkdir -p "${RO_LATEST}"
          cp -a "${RO_DIR}/." "${RO_LEST}/" 2>/dev/null || cp -a "${RO_DIR}/." "${RO_LATEST}/"

          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "[ci] try-theme logs ${RUN_ID}" || echo "Nothing to commit"
          git push origin HEAD:${GITHUB_REF_NAME:-main} || echo "[WARN] push failed"
