# .github/workflows/98_fix_headers.yml
name: 98_fix_headers (purge + HTTP opcache reset)
on: { workflow_dispatch: {} }
permissions: { contents: read }

jobs:
  fix:
    runs-on: ubuntu-latest
    env:
      HOST:   ${{ secrets.DEPLOY_HOST }}
      PORT:   ${{ secrets.DEPLOY_PORT }}
      USER:   ${{ secrets.DEPLOY_USER }}
      PASS:   ${{ secrets.DEPLOY_PASS }}
      TARGET: ${{ secrets.DEPLOY_TARGET }}
    steps:
      - name: Purge wtp-fatal-catcher + create once HTTP opcache reset
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ env.HOST }}
          port: ${{ env.PORT }}
          username: ${{ env.USER }}
          password: ${{ env.PASS }}
          envs: TARGET
          command_timeout: 5m
          script: |
            set -euo pipefail

            # 1) Wejście do WP
            if [ -n "${TARGET:-}" ]; then cd "${TARGET}"; else cd "${HOME}/public_html"; fi
            echo "[PWD] $(pwd)"

            echo "[BEFORE] mu-plugins:"
            ls -la wp-content/mu-plugins | head -n 200 || true

            # 2) Usuń KAŻDY wtp-fatal-catcher.php
            find . -type f -name 'wtp-fatal-catcher.php' -print -delete 2>/dev/null || true
            find wp-content/mu-plugins -maxdepth 1 -type f -name '*fatal*catcher*.php*' -print -delete 2>/dev/null || true

            # 3) Sterylny 00-mu-safe-loader.php (zero outputu)
            cat > wp-content/mu-plugins/00-mu-safe-loader.php <<'PHP'
            <?php
            if (!defined('ABSPATH')) { exit; }
            add_action('muplugins_loaded', static function () {
                // no output
            }, 0);
            PHP
            chmod 0644 wp-content/mu-plugins/00-mu-safe-loader.php || true

            echo "[AFTER] mu-plugins:"
            ls -la wp-content/mu-plugins | head -n 200 || true

            # 4) Zbuduj jednorazowy plik HTTP do resetu OPcache (hit przez CURL)
            cat > wtp-reset-opcache.php <<'PHP'
            <?php
            if (function_exists('opcache_reset')) { opcache_reset(); }
            header('Content-Type: text/plain; charset=utf-8');
            echo "OPCACHE_RESET_OK\n";
            @unlink(__FILE__); // samosprzątanie
            PHP
            chmod 0644 wtp-reset-opcache.php || true

            # 5) Ustal URL strony i odpal HTTP reset
            SITE="$(php ./wp option get siteurl 2>/dev/null || true)"
            echo "[SITE] $SITE"
            if [ -n "$SITE" ]; then
              curl -fsSL "$SITE/wtp-reset-opcache.php" || true
            else
              echo "[WARN] Nie ustaliłem siteurl – reset pozostanie pod plikiem, wejdź ręcznie: /wtp-reset-opcache.php"
            fi

            # 6) Diagnostyka: czy gdzieś jeszcze jest catcher (poza .wtp/snapshot)?
            echo "[SCAN] residual:"
            find . -type f -name 'wtp-fatal-catcher.php' -not -path './.wtp/*' -print 2>/dev/null || true
