name: 99_ssh_hotfix
on: { workflow_dispatch: {} }
permissions: { contents: read }

jobs:
  fix:
    runs-on: ubuntu-latest
    env:
      HOST:   ${{ secrets.DEPLOY_HOST }}
      PORT:   ${{ secrets.DEPLOY_PORT }}
      USER:   ${{ secrets.DEPLOY_USER }}
      PASS:   ${{ secrets.DEPLOY_PASS }}
      TARGET: ${{ secrets.DEPLOY_TARGET }}
    steps:
      - name: Hotfix MU loader (no fail, always continue)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ env.HOST }}
          username: ${{ env.USER }}
          password: ${{ env.PASS }}
          port: ${{ env.PORT }}
          # UDOSTĘPNIAMY TARGET na serwerze:
          envs: TARGET
          script_stop: false
          command_timeout: 3m
          script: |
            # Nie używamy "set -e"; sami pilnujemy błędów.
            set -uo pipefail

            # 1) Wejdź do katalogu WP
            if [ -n "${TARGET:-}" ]; then
              cd "${TARGET}" 2>/dev/null || true
            else
              cd '${{ env.TARGET }}' 2>/dev/null || true
            fi
            # Fallback (gdy sekret byłby pusty):
            [ -d "wp-content" ] || cd "${HOME}/public_html" 2>/dev/null || true

            echo "== PWD =="; pwd || true

            echo "== BEFORE =="; ls -la wp-content/mu-plugins | head -n 200 || true

            # 2) Usuń ewentualny zepsuty catcher
            BAD="wp-content/mu-plugins/wtp-fatal-catcher.php"
            if [ -f "$BAD" ]; then
              rm -f "$BAD" || echo "[WARN] Can't remove $BAD"
              echo "Removed $BAD"
            else
              echo "No $BAD (ok)"
            fi

            # 3) Zapisz sterylny safe-loader (zero outputu, zero spacji przed <?php)
            cat > wp-content/mu-plugins/00-mu-safe-loader.php <<'PHP'
            <?php
            if (!defined('ABSPATH')) { exit; }
            add_action('muplugins_loaded', static function () {
                // no output
            }, 0);
            PHP
            chmod 0644 wp-content/mu-plugins/00-mu-safe-loader.php || true

            # 4) Spróbuj zresetować OPcache, ale nie zrywaj sesji, jeśli PHP/OPcache brak
            if command -v php >/dev/null 2>&1; then
              php -r 'if(function_exists("opcache_reset")){opcache_reset();echo "OPCACHE_RESET_OK\n";}else{echo "NO_OPCACHE\n";}'
            else
              echo "[WARN] php not found in PATH (skip opcache reset)"
            fi

            echo "== AFTER =="; ls -la wp-content/mu-plugins | head -n 200 || true

            # 5) Nigdy nie kończ błędem (to hotfix)
            exit 0
