name: 98_fix_headers (neutralize fatal-catcher + opcache invalidate)
on: { workflow_dispatch: {} }
permissions: { contents: read }

jobs:
  fix:
    runs-on: ubuntu-latest
    env:
      HOST:   ${{ secrets.DEPLOY_HOST }}
      PORT:   ${{ secrets.DEPLOY_PORT }}
      USER:   ${{ secrets.DEPLOY_USER }}
      PASS:   ${{ secrets.DEPLOY_PASS }}
      TARGET: ${{ secrets.DEPLOY_TARGET }}
    steps:
      - name: Neutralize wtp-fatal-catcher.php + invalidate OPcache
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ env.HOST }}
          port: ${{ env.PORT }}
          username: ${{ env.USER }}
          password: ${{ env.PASS }}
          envs: TARGET
          command_timeout: 5m
          script: |
            set -euo pipefail
            # 1) Wejście do WP
            if [ -n "${TARGET:-}" ]; then cd "${TARGET}"; else cd "${HOME}/public_html"; fi
            echo "[PWD] $(pwd)"

            MU="wp-content/mu-plugins"
            CATCHER="${MU}/wtp-fatal-catcher.php"

            echo "== BEFORE =="
            ls -la "${MU}" | sed -n '1,200p' || true

            # 2) Utwórz całkowicie cichy plik catcher (nawet jeśli nie istnieje – nadpisujemy bezpieczną wersją)
            mkdir -p "${MU}"
            cat > "${CATCHER}" <<'PHP'
            <?php
            // silent placeholder - no BOM, no output
            if (!defined('ABSPATH')) { exit; }
            PHP
            chmod 0644 "${CATCHER}"

            # 3) Dodatkowo upewnij się, że nasz 00 loader jest sterylny
            cat > "${MU}/00-mu-safe-loader.php" <<'PHP'
            <?php
            if (!defined('ABSPATH')) { exit; }
            add_action('muplugins_loaded', static function () {
                // no output
            }, 0);
            PHP
            chmod 0644 "${MU}/00-mu-safe-loader.php"

            # 4) Invalidate OPcache dokładnie dla catcher'a (CLI)
            php -r 'function i($p){if(function_exists("opcache_invalidate")){var_dump(opcache_invalidate($p,true));}else{echo "NO_OPCACHE\n";}} i("'${CATCHER}'");' || true

            # 5) Jednorazowy HTTP reset całej puli (gdyby CLI nie wystarczył)
            cat > wtp-reset-opcache.php <<'PHP'
            <?php
            if (function_exists('opcache_reset')) { opcache_reset(); }
            header('Content-Type: text/plain; charset=utf-8');
            echo "OPCACHE_RESET_OK\n";
            @unlink(__FILE__);
            PHP
            SITE="$(php ./wp option get siteurl 2>/dev/null || true)"
            echo "[SITE] $SITE"
            if [ -n "$SITE" ]; then curl -fsSL "$SITE/wtp-reset-opcache.php" || true; fi

            echo "== AFTER =="
            head -n 5 "${CATCHER}" || true
            ls -la "${MU}" | sed -n '1,200p' || true
