name: Agent Push

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'plugins/**'
      - 'plugins/manifest.json'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    env:
      PLUGIN_GLOB: "wtp-*"
      ZIP_OUT_DIR: "plugins"
      MANIFEST_PATH: "plugins/manifest.json"
      RAW_BASE: "https://raw.githubusercontent.com/${{ github.repository }}/main/plugins"

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Prepare output dir
        run: mkdir -p "$ZIP_OUT_DIR"

      - name: Zip plugins
        run: |
          shopt -s nullglob
          for dir in $PLUGIN_GLOB; do
            [ -d "$dir" ] || continue
            zip -r "$ZIP_OUT_DIR/$dir.zip" "$dir" >/dev/null
          done
          ls -l "$ZIP_OUT_DIR" || true

      - name: Build manifest.json
        run: |
          echo "[" > "$MANIFEST_PATH"
          first=1
          for z in $ZIP_OUT_DIR/*.zip; do
            [ -e "$z" ] || continue
            fname=$(basename "$z")
            name="${fname%.zip}"
            sum=$(sha256sum "$z" | awk '{print $1}')
            url="${RAW_BASE}/${fname}"
            item="{\"name\":\"${name}\",\"url\":\"${url}\",\"version\":\"${sum}\"}"
            if [ $first -eq 1 ]; then
              echo "  $item" >> "$MANIFEST_PATH"; first=0
            else
              echo " ,$item" >> "$MANIFEST_PATH"
            fi
          done
          echo "]" >> "$MANIFEST_PATH"
          cat "$MANIFEST_PATH"

      - name: Commit ZIPs + manifest
        run: |
          git config user.name "wtp-agent"
          git config user.email "wtp-agent@users.noreply.github.com"
          git add "$ZIP_OUT_DIR"/*.zip "$MANIFEST_PATH" || true
          if ! git diff --cached --quiet; then
            git commit -m "agent: publish zips & manifest [skip ci]"
            git push
          else
            echo "No changes."
          fi

      - name: Trigger WTP Push runner
        env:
          RUNNER_URL: ${{ secrets.RUNNER_URL }}
          RUNNER_SECRET: ${{ secrets.WTP_AGENT_TOKEN }}
        run: |
          MANIFEST_URL="${{ env.RAW_BASE }}/manifest.json"
          curl -fSs -X POST "$RUNNER_URL" \
            -H "Content-Type: application/json" \
            -d "{\"secret\":\"$RUNNER_SECRET\",\"manifest\":\"$MANIFEST_URL\"}"
