name: AI Upsert File

on:
  repository_dispatch:
    types: [ai-upsert-file]
  workflow_dispatch:
    inputs:
      path:
        description: 'Target path in repo (e.g., mu-plugins/00-mu-safe-loader.php)'
        required: true
        type: string
      content_b64:
        description: 'File content (Base64). Leave empty if you use content_plain.'
        required: false
        type: string
      content_plain:
        description: 'File content (plain text). Will be Base64-encoded in the job.'
        required: false
        type: string
      message:
        description: 'Commit message'
        required: true
        type: string
      branch:
        description: 'Target branch'
        required: false
        default: 'main'
        type: string
      sha256:
        description: 'Optional SHA-256 of decoded content'
        required: false
        type: string

permissions:
  contents: write

concurrency:
  group: ai-upsert-file
  cancel-in-progress: true

jobs:
  upsert:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      GH_REPO: ${{ github.repository }}
      # Użyj prywatnego PAT jeśli jest; inaczej fallback do wbudowanego tokena
      GH_TOKEN: ${{ secrets.WTP_GITHUB_PAT != '' && secrets.WTP_GITHUB_PAT || github.token }}

    steps:
      - name: Resolve inputs / payload (UI vs repository_dispatch)
        id: inp
        shell: bash
        run: |
          set -euo pipefail

          # Domyślne wartości (UI)
          PATH_IN="${{ inputs.path }}"
          CONTENT_B64="${{ inputs.content_b64 }}"
          CONTENT_PLAIN="${{ inputs.content_plain }}"
          MESSAGE="${{ inputs.message }}"
          BRANCH="${{ inputs.branch }}"
          SHA256_OPT="${{ inputs.sha256 }}"

          # Jeśli event to repository_dispatch – nadpisz danymi z client_payload
          if [ "${GITHUB_EVENT_NAME}" = "repository_dispatch" ]; then
            PATH_IN="$(python3 - <<'PY'
import json, os
j=json.load(open(os.environ["GITHUB_EVENT_PATH"], "r"))
print(j.get("client_payload",{}).get("path",""))
PY
)"
            CONTENT_B64="$(python3 - <<'PY'
import json, os
j=json.load(open(os.environ["GITHUB_EVENT_PATH"], "r"))
print(j.get("client_payload",{}).get("content_b64",""))
PY
)"
            CONTENT_PLAIN="$(python3 - <<'PY'
import json, os
j=json.load(open(os.environ["GITHUB_EVENT_PATH"], "r"))
print(j.get("client_payload",{}).get("content_plain",""))
PY
)"
            MESSAGE="$(python3 - <<'PY'
import json, os
j=json.load(open(os.environ["GITHUB_EVENT_PATH"], "r"))
print(j.get("client_payload",{}).get("message",""))
PY
)"
            BRANCH="$(python3 - <<'PY'
import json, os
j=json.load(open(os.environ["GITHUB_EVENT_PATH"], "r"))
print(j.get("client_payload",{}).get("branch","main"))
PY
)"
            SHA256_OPT="$(python3 - <<'PY'
import json, os
j=json.load(open(os.environ["GITHUB_EVENT_PATH"], "r"))
print(j.get("client_payload",{}).get("sha256",""))
PY
)"
          fi

          # Walidacje podstawowe
          if [ -z "${PATH_IN}" ] || [ -z "${MESSAGE}" ]; then
            echo "::error::Missing required 'path' or 'message'."
            exit 1
          fi

          # Jeśli nie ma base64, a jest plain → zakoduj w Pythonie (bez łamań linii)
          if [ -z "${CONTENT_B64}" ] && [ -n "${CONTENT_PLAIN}" ]; then
            CONTENT_B64="$(python3 - <<'PY'
import base64, os, sys
data = os.environ["CONTENT_PLAIN"].encode("utf-8")
print(base64.b64encode(data).decode("ascii"))
PY
)"
          fi

          if [ -z "${CONTENT_B64}" ]; then
            echo "::error::Provide content_b64 or content_plain."
            exit 1
          fi

          # Opcjonalne SHA-256
          if [ -n "${SHA256_OPT}" ]; then
            CALC="$(python3 - <<'PY'
import base64, hashlib, os
raw = base64.b64decode(os.environ["CONTENT_B64"].encode("ascii"), validate=True)
print(hashlib.sha256(raw).hexdigest())
PY
)"
            echo "expected=${SHA256_OPT}"
            echo "calculated=${CALC}"
            if [ "${SHA256_OPT}" != "${CALC}" ]; then
              echo "::error::SHA-256 mismatch."
              exit 1
            fi
          fi

          {
            echo "path=${PATH_IN}"
            echo "branch=${BRANCH}"
            echo "message<<EOF"
            echo "${MESSAGE}"
            echo "EOF"
            echo "content_b64<<EOF"
            echo "${CONTENT_B64}"
            echo "EOF"
          } >> "$GITHUB_OUTPUT"

      - name: Get current file SHA (if exists)
        id: cur
        shell: bash
        env:
          PATH_IN: ${{ steps.inp.outputs.path }}
        run: |
          set -euo pipefail
          PATH_ENC="$(python3 - <<'PY'
import urllib.parse, os
print(urllib.parse.quote(os.environ["PATH_IN"], safe=""))
PY
)"
          API="https://api.github.com/repos/${GH_REPO}/contents/${PATH_ENC}?ref=${{ steps.inp.outputs.branch }}"
          echo "GET $API"
          set +e
          RESP="$(curl -fsS -H "Authorization: Bearer ${GH_TOKEN}" -H "Accept: application/vnd.github+json" "$API")"
          CODE=$?
          set -e
          if [ $CODE -eq 0 ]; then
            SHA="$(python3 - <<'PY'
import json, os
j=json.loads(os.environ["RESP"])
print(j.get("sha",""))
PY
)"
            echo "sha=${SHA}" >> "$GITHUB_OUTPUT"
          else
            echo "sha=" >> "$GITHUB_OUTPUT"
          fi

      - name: Create/Update file (PUT)
        shell: bash
        env:
          PATH_IN: ${{ steps.inp.outputs.path }}
          BRANCH:  ${{ steps.inp.outputs.branch }}
          MESSAGE: ${{ steps.inp.outputs.message }}
          B64:     ${{ steps.inp.outputs.content_b64 }}
          CUR_SHA: ${{ steps.cur.outputs.sha }}
        run: |
          set -euo pipefail
          BODY="$(python3 - <<'PY'
import json, os
payload = {
  "message": os.environ["MESSAGE"],
  "content": os.environ["B64"],
  "branch":  os.environ["BRANCH"],
}
sha = os.environ.get("CUR_SHA", "")
if sha:
    payload["sha"] = sha
print(json.dumps(payload, separators=(",",":")))
PY
)"
          PATH_ENC="$(python3 - <<'PY'
import urllib.parse, os
print(urllib.parse.quote(os.environ["PATH_IN"], safe=""))
PY
)"
          API="https://api.github.com/repos/${GH_REPO}/contents/${PATH_ENC}"
          echo "PUT $API"
          RESP="$(curl -fsS -X PUT "$API" \
            -H "Authorization: Bearer ${GH_TOKEN}" \
            -H "Accept: application/vnd.github+json" \
            -d "$BODY")"
          echo "$RESP" | python3 - <<'PY'
import json, sys
r=json.loads(sys.stdin.read())
ok = ("content" in r) or ("commit" in r)
print(json.dumps({
  "ok": ok,
  "path": (r.get("content") or {}).get("path",""),
  "commit": (r.get("commit") or {}).get("sha","")
}, indent=2))
sys.exit(0 if ok else 1)
PY

      - name: Summary
        run: |
          echo "✅ Upserted: ${{ steps.inp.outputs.path }} on branch ${{ steps.inp.outputs.branch }}"
