name: Apply Inbox Patch

on:
  push:
    branches: [ main ]
    paths:
      - '.wtp/inbox/'
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: apply-inbox-patch
  cancel-in-progress: false

jobs:
  apply:
    name: Apply patches from .wtp/inbox
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Find patches
        id: find
        shell: bash
        run: |
          shopt -s nullglob
          files=(.wtp/inbox/*.patch)
          if [ ${#files[@]} -eq 0 ]; then
            echo "found=false" >> "$GITHUB_OUTPUT"
            echo "No patch in this push"
            exit 0
          fi
          printf '%s\n' "${files[@]}" > /tmp/patch_list.txt
          echo "found=true" >> "$GITHUB_OUTPUT"
          echo "count=${#files[@]}" >> "$GITHUB_OUTPUT"

      - name: Apply patches
        if: steps.find.outputs.found == 'true'
        shell: bash
        run: |
          set -euo pipefail
          while IFS= read -r p; do
            echo "Applying: $p"
            git apply --index "$p"
            mkdir -p .wtp/processed
            mv "$p" ".wtp/processed/$(basename "$p")"
          done < /tmp/patch_list.txt

      - name: Commit & push
        if: steps.find.outputs.found == 'true'
        shell: bash
        run: |
          git config user.name  "wtp-bot"
          git config user.email "wtp-bot@users.noreply.github.com"
          git commit -m "[apply-inbox] apply ${GITHUB_SHA::7} patches from inbox -> processed [skip ci]" || echo "No changes"
          git push
