name: Apply Inbox Patch

on:
  push:
    paths:
      - ".wtp/inbox/.patch"
      - ".github/workflows/apply-inbox-patch.yml"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  apply:
    name: Apply patch files from .wtp/inbox
    runs-on: ubuntu-latest

    steps:
      - name: Checkout (full history)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure git
        run: |
          git config user.name  "wtp-bot"
          git config user.email "wtp-bot@users.noreply.github.com"

      - name: Find patches
        id: find
        shell: bash
        run: |
          set -euo pipefail
          shopt -s nullglob
          files=(.wtp/inbox/*.patch)
          if [ ${#files[@]} -eq 0 ]; then
            echo "found=0" >> "$GITHUB_OUTPUT"
            echo "No patches found in this commit. Skipping."
            exit 0
          fi
          printf "%s\n" "${files[@]}" > patch_list.txt
          echo "found=${#files[@]}" >> "$GITHUB_OUTPUT"
          echo "list<<EOF" >> "$GITHUB_OUTPUT"
          cat patch_list.txt >> "$GITHUB_OUTPUT"
          echo "EOF" >> "$GITHUB_OUTPUT"
          cat patch_list.txt

      - name: Apply patches
        if: steps.find.outputs.found != '0'
        shell: bash
        run: |
          set -euo pipefail
          while read -r p; do
            echo "::group::Applying $p"
            git apply --index --reject "$p"
            echo "::endgroup::"
          done < patch_list.txt

      - name: Commit & push changes
        if: steps.find.outputs.found != '0'
        shell: bash
        run: |
          set -euo pipefail
          if ! git diff --cached --quiet; then
            msg="apply-inbox: $(wc -l < patch_list.txt) patch(es)"
            git commit -m "$msg"
            git push
            echo "Committed and pushed."
          else
            echo "Nothing to commit after applying patches."
          fi
