name: Apply Inbox Patch

on:
  push:
    branches:
      - ''                 # dowolna gałąź
    paths:
      - '.wtp/inbox/'      # tylko zmiany w inbox
  pull_request:
    branches:
      - main
    paths:
      - '.wtp/inbox/'
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  apply:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Ensure tools
        run: |
          set -euo pipefail
          sudo apt-get update -y
          sudo apt-get install -y git

      - name: Find first patch in .wtp/inbox
        id: find
        shell: bash
        run: |
          set -euo pipefail
          PATCH="$(ls -1 .wtp/inbox/*.patch 2>/dev/null | head -n1 || true)"
          if [ -z "$PATCH" ]; then
            echo "No patch in this push"
            exit 0
          fi
          echo "patch=$PATCH" >> "$GITHUB_OUTPUT"

      - name: Apply patch
        if: steps.find.outputs.patch
        shell: bash
        run: |
          set -euo pipefail
          git config user.name  "wtp-bot"
          git config user.email "wtp-bot@users.noreply.github.com"

          PATCH="${{ steps.find.outputs.patch }}"
          echo "Applying: $PATCH"
          git apply --3way --index "$PATCH"

          # Commit zmian
          git commit -m "[apply-inbox] $(basename "$PATCH") [skip ci]"

          # Przenieś patch do processed (archiwizacja)
          mkdir -p .wtp/processed
          mv "$PATCH" ".wtp/processed/$(basename "$PATCH")"

          # Commit archiwizacji (też z [skip ci] by uniknąć pętli)
          git add .wtp/processed
          git commit -m "[apply-inbox] archive $(basename "$PATCH") [skip ci]" || true

          # Push na tę samą gałąź
          git push origin HEAD
