name: Apply Inbox Patch

on:
  push:
    branches: [ main ]
    paths:
      - '.wtp/inbox/*.patch'
  workflow_dispatch: {}

jobs:
  apply:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Git config
        run: |
          git config user.name  "wtp-bot"
          git config user.email "wtp-bot@users.noreply.github.com"

      - name: Ensure folders
        run: |
          mkdir -p .wtp/inbox .wtp/processed

      - name: Apply all patches from inbox (idempotent)
        shell: bash
        run: |
          set -euo pipefail
          shopt -s nullglob

          PATCHES=(.wtp/inbox/*.patch)
          if [ ${#PATCHES[@]} -eq 0 ]; then
            echo "Inbox empty. Nothing to do."
            exit 0
          fi

          for P in "${PATCHES[@]}"; do
            BN="$(basename "$P")"
            echo ">> Applying: $BN"

            # spróbuj 3-way; jeśli brak zmian/already applied – nie traktuj jako błąd
            if git apply --check --3way "$P"; then
              git apply --3way "$P"
              echo "Applied: $BN"
            else
              echo "Nothing to apply or already applied: $BN (ok)"
            fi

            # archiwizacja do .wtp/processed z nadpisaniem jeżeli istnieje
            TARGET=".wtp/processed/$BN"
            if [ -e "$TARGET" ]; then
              echo "Processed already has $BN – replacing."
              git rm -f "$TARGET" 2>/dev/null || rm -f "$TARGET" || true
            fi
            git mv "$P" "$TARGET"
          done

          # commit tylko jeśli cokolwiek się zmieniło (aplikacja łatki lub przeniesienia)
          git add -A || true
          if git diff --cached --quiet; then
            echo "No repo changes to commit."
            exit 0
          fi

          git commit -m "[apply-inbox] processed patches"
          git push origin HEAD:main
          echo "Done."
