name: Apply Inbox Patch

on:
  push:
    branches: [ main ]
    paths:
      - '.wtp/inbox/'
  workflow_dispatch: {}

jobs:
  apply:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Git config
        run: |
          git config user.name  "wtp-bot"
          git config user.email "wtp-bot@users.noreply.github.com"

      - name: Ensure folders
        run: |
          mkdir -p .wtp/inbox .wtp/processed

      - name: Apply all patches from inbox (timestamped archive)
        shell: bash
        run: |
          set -euo pipefail
          shopt -s nullglob

          PATCHES=(.wtp/inbox/*.patch)
          if [ ${#PATCHES[@]} -eq 0 ]; then
            echo "Inbox empty. Nothing to do."
            exit 0
          fi

          changes=0
          ts() { date -u +%Y%m%dT%H%M%SZ; }

          for P in "${PATCHES[@]}"; do
            BN="$(basename "$P")"
            BASE="${BN%.patch}"
            STAMP="$(ts)"

            echo ">> Processing: $BN"

            status="skipped"
            # najpierw sprawdź, czy patch da się zastosować 3-way
            if git apply --check --3way "$P" 2>/dev/null; then
              # zastosuj
              if git apply --3way "$P"; then
                status="applied"
                changes=1
                echo "   Applied: $BN"
              else
                status="failed"
                echo "   WARN: apply failed at runtime: $BN"
              fi
            else
              # jeśli --check nie przeszło, może już w repo (brak zmian) – to OK
              status="skipped"
              echo "   No changes (already applied?): $BN"
            fi

            # przenieś do processed z TSTAMP i statusem – bez kolizji
            DEST=".wtp/processed/${BASE}-${status}-${STAMP}.patch"
            # jeśli plik już istnieje (teoretycznie nie powinien), dopnij losowy sufiks
            if [ -e "$DEST" ]; then
              DEST=".wtp/processed/${BASE}-${status}-${STAMP}-$(openssl rand -hex 3).patch"
            fi

            git rm -f --cached --quiet "$P" 2>/dev/null || true   # na wypadek staged
            mv "$P" "$DEST"
            git add "$DEST" || true
          done

          # Commit tylko jeśli są zmiany w drzewie
          if ! git diff --cached --quiet; then
            git commit -m "[apply-inbox] processed patches ($(date -u +%Y-%m-%dT%H:%M:%SZ))"
            git push origin HEAD:main
            echo "Pushed processed patches."
          else
            echo "No repo changes to commit."
          fi

          # Nie zabijaj joba, jeśli żaden patch nie wniósł zmian — to normalne
          exit 0
