name: Apply Inbox Patch

on:
  push:
    # łap wszystko (również zmiany robione z UI), ale filtrujemy w if: później
    branches: [ "" ]
  workflow_dispatch: {}

jobs:
  apply:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name  "wtp-bot"
          git config user.email "wtp-bot@users.noreply.github.com"

      - name: Ensure folders
        run: |
          mkdir -p .wtp/inbox .wtp/processed

      - name: Apply patches from inbox (only if any .patch changed)
        shell: bash
        run: |
          set -euo pipefail
          shopt -s nullglob

          # sprawdź czy w tym commicie dotknięto .wtp/inbox/*.patch
          echo "Changed files:"
          git diff --name-only HEAD~1..HEAD || true

          CHANGED_PATCHES=$(git diff --name-only HEAD~1..HEAD | grep -E '^\.wtp/inbox/.+\.patch$' || true)
          if [ -z "$CHANGED_PATCHES" ]; then
            echo "No .wtp/inbox/*.patch in this push; exiting 0."
            exit 0
          fi

          PATCHES=(.wtp/inbox/*.patch)
          if [ ${#PATCHES[@]} -eq 0 ]; then
            echo "Inbox empty."
            exit 0
          fi

          for P in "${PATCHES[@]}"; do
            BN="$(basename "$P")"
            echo ">> Applying: $BN"

            # Spróbuj 3-way; jeżeli nic do zmiany – nie traktuj jako błąd
            if git apply --check --3way "$P"; then
              git apply --3way "$P"
              echo "Applied cleanly: $BN"
            else
              echo "Nothing to apply or already applied: $BN (continuing)"
            fi

            git add -A || true
            if git diff --cached --quiet; then
              echo "No changes to commit after $BN"
            else
              git commit -m "[apply-inbox] $BN"
              git push origin HEAD:main
            fi

            # Archiwizuj, żeby nie zapętlać
            mv "$P" ".wtp/processed/$BN" || true
          done

          echo "All patches processed."
