name: Apply Inbox Patch

on:
  push:
    paths:
      - ".wtp/inbox/*.patch"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  apply:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Ensure tools
        run: |
          sudo apt-get update -y
          sudo apt-get install -y git

      - name: Find first patch in .wtp/inbox
        id: find
        run: |
          set -euo pipefail
          PATCH="$(ls -1 .wtp/inbox/*.patch 2>/dev/null | head -n1 || true)"
          if [ -z "$PATCH" ]; then
            echo "patch=" >> "$GITHUB_OUTPUT"
            exit 0
          fi
          echo "patch=$PATCH" >> "$GITHUB_OUTPUT"

      - name: Apply patch
        if: steps.find.outputs.patch != ''
        run: |
          set -euo pipefail
          git config user.name  "wtp-bot"
          git config user.email "wtp-bot@users.noreply.github.com"

          PATCH="${{ steps.find.outputs.patch }}"
          echo "Applying: $PATCH"
          git apply --3way --index "$PATCH"

          git commit -m "[apply-inbox] $(basename "$PATCH") [skip ci]"

          mkdir -p .wtp/processed
          mv "$PATCH" ".wtp/processed/$(basename "$PATCH")"

          git add .wtp/processed
          git commit -m "[apply-inbox] archive $(basename "$PATCH") [skip ci]" || true

          git push origin HEAD
