name: Apply Inbox Patch

on:
  push:
    branches: [ main ]
    paths:
      - ".wtp/inbox/*.patch"
  workflow_dispatch: {}

jobs:
  apply:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name  "wtp-bot"
          git config user.email "wtp-bot@users.noreply.github.com"

      - name: Ensure folders
        run: |
          mkdir -p .wtp/inbox .wtp/processed

      - name: Apply patches
        shell: bash
        run: |
          set -euo pipefail
          shopt -s nullglob
          PATCHES=(.wtp/inbox/*.patch)

          if [ ${#PATCHES[@]} -eq 0 ]; then
            echo "No patches to apply."
            exit 0
          fi

          for P in "${PATCHES[@]}"; do
            echo ">> Applying: $P"

            # Spróbuj 3-way; jeśli patch pusty/już zastosowany – nie przerywaj
            if git apply --check --3way "$P"; then
              git apply --3way "$P"
              echo "Applied cleanly: $P"
            else
              echo "Patch may be empty or already applied, trying relaxed -3"
              git apply -3 "$P" || echo "No hunks applied (already in tree?)"
            fi

            # Zawsze przenieś do processed, by nie zapętlać
            BN="$(basename "$P")"
            mv "$P" ".wtp/processed/$BN"

            # Zacommituj TYLKO jeśli są zmiany
            git add -A || true
            if git diff --cached --quiet; then
              echo "No changes to commit after $BN"
            else
              git commit -m "[apply-inbox] $BN"
              git push origin HEAD:main
            fi
          done

          echo "All patches processed."
