name: "CI Logs: digest & report"

on:
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  digest:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Prepare report
        shell: bash
        run: |
          set -euo pipefail
          REPORT=".wtp/reports/ci-digest-${GITHUB_RUN_ID}.md"
          mkdir -p .wtp/reports
          echo "# CI logs digest – run ${GITHUB_RUN_ID}" > "$REPORT"
          echo "" >> "$REPORT"
          if [ ! -d ".wtp/state/ci_logs" ]; then
            echo "Brak katalogu .wtp/state/ci_logs" >> "$REPORT"
            exit 0
          fi

          echo "## Files" >> "$REPORT"
          find .wtp/state/ci_logs -type f -maxdepth 1 | sort > /tmp/ci_files.txt || true
          if [ ! -s /tmp/ci_files.txt ]; then
            echo "_No log files in .wtp/state/ci_logs_" >> "$REPORT"
            exit 0
          fi
          echo '```' >> "$REPORT"
          cat /tmp/ci_files.txt >> "$REPORT"
          echo '```' >> "$REPORT"

          echo "" >> "$REPORT"
          echo "## Heuristics (errors & warnings)" >> "$REPORT"
          echo "" >> "$REPORT"
          touch /tmp/hits.txt

          grep -RInE "wp-?cli not (executable|working)|unbound variable|unexpected end of filter rule: merge|rsync error|rsync.*\(code [0-9]+\)|curl: \(22\)|404|could not parse as YAML|mapping values are not allowed in this context" \
              .wtp/state/ci_logs || true | tee /tmp/hits.txt

          if [ -s /tmp/hits.txt ]; then
            echo '```' >> "$REPORT"
            cat /tmp/hits.txt >> "$REPORT"
            echo '```' >> "$REPORT"
          else
            echo "_No known error patterns found._" >> "$REPORT"
          fi

          echo "" >> "$REPORT"
          echo "## Tail (last 80 lines per file)" >> "$REPORT"
          echo "" >> "$REPORT"
          while IFS= read -r f; do
            echo "### ${f}" >> "$REPORT"
            echo '```' >> "$REPORT"
            tail -n 80 "$f" >> "$REPORT" || true
            echo '```' >> "$REPORT"
            echo "" >> "$REPORT"
          done < /tmp/ci_files.txt

      - name: Commit digest
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "ci: add CI logs digest #${{ github.run_id }}"
          file_pattern: ".wtp/reports/ci-digest-*.md"
          branch: main

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ci-digest-${{ github.run_id }}
          path: .wtp/reports/ci-digest-${{ github.run_id }}.md
          retention-days: 7
