name: Deploy to Hostinger (Atomic GH→WP, dry-run, health)

on:
  push:
    branches: [ main ]
    paths:
      - 'mu-plugins/**'
      - 'plugins/**'
      - 'themes/**'
      - 'wp-content/**'
      - '!snapshots/**'
      - '!server-sync/**'
      - '!ops/**'
      - '!.wtp/**'
      - 'docs/locks/**'
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Compute changed files
        id: diff
        shell: bash
        run: |
          set -euo pipefail
          BASE_SHA=$(git rev-parse HEAD~1 || echo "")
          if [ -z "$BASE_SHA" ]; then
            git ls-files > changed.txt
          else
            git diff --name-only "$BASE_SHA"...HEAD > changed.txt
          fi
          awk '/^(mu-plugins|plugins|themes|wp-content)\// {print}' changed.txt > deploy.txt || true
          if [ ! -s deploy.txt ]; then
            echo "nothing=true" >> "$GITHUB_OUTPUT"
          else
            echo "nothing=false" >> "$GITHUB_OUTPUT"
          fi
          echo "Changed (filtered):"
          cat deploy.txt || true

      - name: Stop when nothing to deploy
        if: ${{ steps.diff.outputs.nothing == 'true' }}
        run: echo "No deployable changes."

      - name: Install rsync + sshpass
        if: ${{ steps.diff.outputs.nothing != 'true' }}
        run: |
          sudo apt-get update -y
          sudo apt-get install -y rsync sshpass

      - name: Prepare release bundle (only needed dirs)
        id: prep
        if: ${{ steps.diff.outputs.nothing != 'true' }}
        shell: bash
        run: |
          set -euo pipefail
          REL="release_${GITHUB_SHA::7}"
          mkdir -p "$REL"
          rsync -a \
            --include='mu-plugins/**' \
            --include='plugins/**' \
            --include='themes/**' \
            --include='wp-content/**' \
            --exclude='*' ./ "$REL"/
          tar -czf "${REL}.tar.gz" "$REL"
          echo "REL=${REL}" >> "$GITHUB_OUTPUT"
          ls -lah "${REL}.tar.gz"

      - name: Dry-run sanity (preview bundle)
        if: ${{ steps.diff.outputs.nothing != 'true' }}
        shell: bash
        run: |
          set -euo pipefail
          REL="${{ steps.prep.outputs.REL }}"
          echo "=== Bundle tree (first 200) ==="
          tar -tzf "${REL}.tar.gz" | head -n 200 || true
          echo "=== Verify expected dirs ==="
          if tar -tzf "${REL}.tar.gz" | grep -E "^${REL}/(plugins|themes|mu-plugins)/" >/dev/null; then
            echo "OK: plugins/themes/mu-plugins present"
          else
            echo "::error::Bundle missing expected dirs"
            exit 2
          fi
          echo "=== File count ==="
          tar -tzf "${REL}.tar.gz" | wc -l

      - name: Upload bundle to server
        if: ${{ steps.diff.outputs.nothing != 'true' }}
        env:
          HOST:   ${{ secrets.DEPLOY_HOST }}
          USER:   ${{ secrets.DEPLOY_USER }}
          PASS:   ${{ secrets.DEPLOY_PASS }}
          PORT:   ${{ secrets.DEPLOY_PORT }}
          TARGET: ${{ secrets.DEPLOY_TARGET }}
        shell: bash
        run: |
          set -euo pipefail
          REL="${{ steps.prep.outputs.REL }}"
          sshpass -p "$PASS" scp -P "${PORT:-22}" -o StrictHostKeyChecking=no "${REL}.tar.gz" "${USER}@${HOST}:${TARGET%/}/"

      - name: Atomic switch (extract + rsync with protect)
        if: ${{ steps.diff.outputs.nothing != 'true' }}
        env:
          HOST:   ${{ secrets.DEPLOY_HOST }}
          USER:   ${{ secrets.DEPLOY_USER }}
          PASS:   ${{ secrets.DEPLOY_PASS }}
          PORT:   ${{ secrets.DEPLOY_PORT }}
          TARGET: ${{ secrets.DEPLOY_TARGET }}
        shell: bash
        run: |
          set -euo pipefail
          # przygotuj skrypt zdalny w zmiennej i wyślij go przez ssh (bez zagnieżdżonych heredoców)
          REMOTE_SCRIPT=$(cat <<'BASH'
set -euo pipefail
cd "$TARGET"

REL_TGZ=$(ls -1 release_*.tar.gz | tail -n1)
if [ -z "$REL_TGZ" ]; then echo "No release_*.tar.gz found"; exit 3; fi
REL_DIR="${REL_TGZ%.tar.gz}"

mkdir -p "releases/${REL_DIR}"
tar -xzf "$REL_TGZ" -C "releases/${REL_DIR}" --strip-components=1

mkdir -p wp-content/plugins wp-content/themes wp-content/mu-plugins

cat > /tmp/wtp-protect.filter <<'EOF'
P wp-content/plugins/litespeed-cache/**
P wp-content/plugins/wordfence/**
P wp-content/plugins/translatepress-multilingual/**
P wp-content/plugins/cookie-law-info/**
EOF

[ -d "releases/${REL_DIR}/plugins" ] && rsync -a --delete --filter="merge /tmp/wtp-protect.filter" "releases/${REL_DIR}/plugins/"    "wp-content/plugins/"    || true
[ -d "releases/${REL_DIR}/themes" ]  && rsync -a --delete "releases/${REL_DIR}/themes/"     "wp-content/themes/"     || true
[ -d "releases/${REL_DIR}/mu-plugins" ] && rsync -a --delete "releases/${REL_DIR}/mu-plugins/" "wp-content/mu-plugins/" || true

date > "wp-content/.wtp_last_deploy"
BASH
)
          # uruchom skrypt na serwerze
          sshpass -p "$PASS" ssh -p "${PORT:-22}" -o StrictHostKeyChecking=no "${USER}@${HOST}" \
            "TARGET='${TARGET%/}' bash -s" <<< "$REMOTE_SCRIPT"

      - name: Post-deploy health (server-side, mandatory)
        if: ${{ steps.diff.outputs.nothing != 'true' }}
        env:
          HOST:   ${{ secrets.DEPLOY_HOST }}
          USER:   ${{ secrets.DEPLOY_USER }}
          PASS:   ${{ secrets.DEPLOY_PASS }}
          PORT:   ${{ secrets.DEPLOY_PORT }}
        shell: bash
        run: |
          set -euo pipefail
          sshpass -p "$PASS" ssh -p "${PORT:-22}" -o StrictHostKeyChecking=no "${USER}@${HOST}" \
            'curl -fsS "http://127.0.0.1/wp-json/wtp-ro-open/v1/health" && echo "Health OK"'

      - name: Purge LiteSpeed cache (server-side, mandatory)
        if: ${{ steps.diff.outputs.nothing != 'true' }}
        env:
          HOST:   ${{ secrets.DEPLOY_HOST }}
          USER:   ${{ secrets.DEPLOY_USER }}
          PASS:   ${{ secrets.DEPLOY_PASS }}
          PORT:   ${{ secrets.DEPLOY_PORT }}
        shell: bash
        run: |
          set -euo pipefail
          sshpass -p "$PASS" ssh -p "${PORT:-22}" -o StrictHostKeyChecking=no "${USER}@${HOST}" \
            'curl -sS "http://127.0.0.1/?LSCWP_CTRL=purge" >/dev/null || true'
