name: Deploy to Hostinger (stub sanity)

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/deploy-to-hostinger.yml'
  workflow_dispatch: {}

jobs:
  stub:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: SSH ping + health (127.0.0.1)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host:     ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          password: ${{ secrets.DEPLOY_PASS }}
          port:     ${{ secrets.DEPLOY_PORT }}
          script: |
            set -e
            echo "Ping server OK"
            curl -fsS "http://127.0.0.1/wp-json/wtp-ro-open/v1/health" >/dev/null
            echo "Health OK"
