name: Generate/Update manifest.json

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Build manifest.json (merge, no overwrite)
        shell: bash
        run: |
          set -euo pipefail
          shopt -s nullglob  # jeśli brak .zip, pętla się nie uruchomi

          [[ -f manifest.json ]] || echo '{"plugins":[]}' > manifest.json

          tmp="$(mktemp)"
          cp manifest.json "$tmp"

          for f in *.zip; do
            name="${f%.zip}"
            url="https://raw.githubusercontent.com/${GITHUB_REPOSITORY}/main/$f"

            # spróbuj wyciągnąć wersję z nazwy pliku (np. my-plugin-1.2.3.zip albo my_plugin_1_2_3.zip)
            if [[ "$f" =~ ([0-9]+\.[0-9]+\.[0-9]+)\.zip$ ]]; then
              v="${BASH_REMATCH[1]}"
            elif [[ "$f" =~ ([0-9]+)_([0-9]+)_([0-9]+)\.zip$ ]]; then
              v="${BASH_REMATCH[1]}.${BASHREMATCH[2]}.${BASH_REMATCH[3]}"
            else
              v="1.0.0"
            fi

            if jq -e --arg n "$name" '.plugins[] | select(.name==$n)' "$tmp" > /dev/null; then
              # aktualizuj istniejący rekord
              jq --arg n "$name" --arg u "$url" --arg v "$v" \
                 '(.plugins[] | select(.name==$n)) |= . + {"url":$u,"version":$v}' "$tmp" > m.json && mv m.json "$tmp"
            else
              # dodaj nowy rekord
              jq --arg n "$name" --arg u "$url" --arg v "$v" \
                 '.plugins += [{"name":$n,"url":$u,"version":$v}]' "$tmp" > m.json && mv m.json "$tmp"
            fi
          done

          mv "$tmp" manifest.json
          jq . manifest.json

      - name: Commit changes (if any)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if git diff --quiet manifest.json; then
            echo "No changes."
          else
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add manifest.json
            git commit -m "auto: update manifest.json"
            git push
          fi

