name: Generate manifest

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate manifest.json
        run: |
          echo '{
            "plugins": [
              {
                "name": "WTP Hello World",
                "url": "https://raw.githubusercontent.com/BoskiDionysos/weektoppick-wp-modules/main/wtp-hello-world.zip",
                "version": "1.0.0"
              },
              {
                "name": "WTP Site Snapshot",
                "url": "https://raw.githubusercontent.com/BoskiDionysos/weektoppick-wp-modules/main/wtp-site-snapshot.zip",
                "version": "0.1.0"
              }
            ]
          }' > manifest.json

      - name: Commit manifest.json
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add manifest.json
          git commit -m "Update manifest.json [skip ci]" || echo "No changes"
          git push
