name: mu-catcher-hunt

on:
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  hunt:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      HOST:   ${{ secrets.DEPLOY_HOST }}
      PORT:   ${{ secrets.DEPLOY_PORT }}
      USER:   ${{ secrets.DEPLOY_USER }}
      PASS:   ${{ secrets.DEPLOY_PASS }}
      TARGET: ${{ secrets.DEPLOY_TARGET }}

    steps:
      - uses: actions/checkout@v4

      - name: Kill catcher + sterilize safe-loader (SSH)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host:     ${{ env.HOST }}
          port:     ${{ env.PORT }}
          username: ${{ env.USER }}
          password: ${{ env.PASS }}
          command_timeout: 3m
          script_stop: true
          envs: TARGET
          script: |
            set -eu

            # Wejście do katalogu WP
            if [ -n "${TARGET:-}" ] && [ -d "${TARGET}" ]; then
              cd "${TARGET}"
            else
              cd "${HOME}/public_html"
            fi
            echo "PWD=$(pwd)"

            echo "== BEFORE =="
            ls -la wp-content/mu-plugins | head -n 200 || true

            # 1) Usuń WSZYSTKIE wtp-fatal-catcher.php (bez bashowych bajerów)
            find wp-content/mu-plugins -type f -name 'wtp-fatal-catcher.php' -print -delete 2>/dev/null || true

            # 2) Twarda, sterylna wersja 00-mu-safe-loader.php (ZERO outputu, ZERO BOM)
            mkdir -p wp-content/mu-plugins
            cat > wp-content/mu-plugins/00-mu-safe-loader.php <<'PHP'
            <?php
            if (!defined('ABSPATH')) { exit; }
            add_action('muplugins_loaded', static function () {
                // silence is golden
            }, 0);
            PHP

            # 3) Reset OPcache (jeśli aktywny)
            php -r 'if(function_exists("opcache_reset")){opcache_reset();echo "OPCACHE_RESET_OK\n";}else{echo "NO_OPCACHE\n";}'

            echo "== AFTER =="
            ls -la wp-content/mu-plugins | head -n 200 || true
