name: mu-catcher-hunt

on:
  workflow_dispatch: {}   # daje przycisk "Run workflow"

permissions:
  contents: read

jobs:
  hunt:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      HOST:   ${{ secrets.DEPLOY_HOST }}
      PORT:   ${{ secrets.DEPLOY_PORT }}
      USER:   ${{ secrets.DEPLOY_USER }}
      PASS:   ${{ secrets.DEPLOY_PASS }}
      TARGET: ${{ secrets.DEPLOY_TARGET }}

    steps:
      - name: Checkout (opcjonalne)
        uses: actions/checkout@v4

      - name: Usuń wtp-fatal-catcher + wysterylizuj 00-mu-safe-loader (SSH)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host:     ${{ env.HOST }}
          port:     ${{ env.PORT }}
          username: ${{ env.USER }}
          password: ${{ env.PASS }}
          envs: TARGET
          command_timeout: 3m
          script_stop: true
          script: |
            set -euo pipefail

            # Wejście do katalogu WP
            if [ -n "${TARGET:-}" ] && [ -d "${TARGET}" ]; then
              cd "${TARGET}"
            else
              cd "${HOME}/public_html"
            fi
            echo "PWD=$(pwd)"

            echo "== BEFORE =="
            ls -la wp-content/mu-plugins | head -n 200 || true

            # 1) Usuń WSZYSTKIE wystąpienia wtp-fatal-catcher.php w mu-plugins
            mapfile -t HITS < <(find wp-content/mu-plugins -type f -name 'wtp-fatal-catcher.php' 2>/dev/null || true)
            if [ "${#HITS[@]}" -gt 0 ]; then
              printf 'Removing %s\n' "${HITS[@]}"
              for f in "${HITS[@]}"; do rm -f "$f"; done
            else
              echo "No wtp-fatal-catcher.php in mu-plugins (good)."
            fi

            # 2) Twarda, sterylna wersja 00-mu-safe-loader.php (zero outputu, zero BOM)
            cat > wp-content/mu-plugins/00-mu-safe-loader.php <<'PHP'
            <?php
            if (!defined('ABSPATH')) { exit; }
            add_action('muplugins_loaded', static function () {
                // silence is golden
            }, 0);
            PHP

            # 3) Reset OPcache (żeby nie brało starej, zepsutej wersji z cache)
            php -r 'if(function_exists("opcache_reset")){opcache_reset(); echo "OPCACHE_RESET_OK\n";} else {echo "NO_OPCACHE\n";}'

            echo "== AFTER =="
            ls -la wp-content/mu-plugins | head -n 200 || true
