name: WTP Snapshot Sync

on:
  schedule:
    - cron: "*/30 * * * *"     # co 30 min (UTC)
  workflow_dispatch: {}
  push:
    branches: [ main ]
    paths:
      - ".github/workflows/wtp-snapshot-sync.yml"

concurrency:
  group: wtp-snapshot-sync
  cancel-in-progress: true

jobs:
  sync:
    runs-on: ubuntu-latest
    env:
      BASE: https://weektoppick.com
      SITE_KEY: 5Depft8Y9LU0t6Sv
      OUTDIR: snapshots/5Depft8Y9LU0t6Sv
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Tools
        run: |
          sudo apt-get update -y
          sudo apt-get install -y jq curl

      - name: Create output dir
        run: |
          mkdir -p "$OUTDIR/logs" || true

      - name: Fetch manifest.json (single source of truth)
        id: ls
        run: |
          set -euo pipefail
          URL="$BASE/wp-json/wtp-ro-open/v1/ls?site_key=$SITE_KEY"
          echo "GET $URL"
          curl -fsS "$URL" -o "$OUTDIR/manifest.json"
          # wypisz listę plików jako output
          FILES=$(jq -r '.list.dirA[] | select(test("^files_\\\\d{3}\\\\.json$"))' "$OUTDIR/manifest.json")
          echo "$FILES" | sed 's/^/file=/'
          echo "count=$(echo "$FILES" | wc -l | xargs)" >> $GITHUB_OUTPUT

      - name: Download all snapshot chunks
        run: |
          set -euo pipefail
          while read -r line; do
            f="${line#file=}"
            [ -z "$f" ] && continue
            echo "→ $f"
            curl -fsS "$BASE/wp-json/wtp-ro-open/v1/get?site_key=$SITE_KEY&file=$f" -o "$OUTDIR/$f"
          done < <(jq -r '.list.dirA[] | select(test("^files_\\d{3}\\.json$")) | "file="+.' "$OUTDIR/manifest.json")

          # pobierz pliki główne, o ile istnieją
          for f in index.json bundle.json options.json selftest.json; do
            curl -fsS "$BASE/wp-json/wtp-ro-open/v1/get?site_key=$SITE_KEY&file=$f" -o "$OUTDIR/$f" || true
          done

      # =============== TU: EMIT-LOGS ===============
      - name: Request fresh logs (/emit-logs)
        run: |
          set -euo pipefail
          curl -fsS -X POST "$BASE/wp-json/wtp-ro-open/v1/emit-logs?site_key=$SITE_KEY" -o /dev/null || true

      - name: Fetch wp-debug + php_errors (best-effort)
        run: |
          set -euo pipefail
          for f in wp-debug-latest.txt php_errors-latest.txt; do
            curl -fsS "$BASE/wp-json/wtp-ro-open/v1/get?site_key=$SITE_KEY&file=$f" -o "$OUTDIR/logs/$f" || true
          done
          # meta (np. rozmiary + mtime wg API)
          curl -fsS "$BASE/wp-json/wtp-ro-open/v1/get?site_key=$SITE_KEY&file=wp-debug-meta.json" -o "$OUTDIR/logs/wp-debug-meta.json" || true

      - name: Commit snapshot (if changed)
        run: |
          set -e
          git add -A
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git config user.name  "wtp-bot"
            git config user.email "wtp-bot@users.noreply.github.com"
            git commit -m "snapshot: ${SITE_KEY} $(date -u +%Y-%m-%dT%H:%M:%SZ)"
            git push origin HEAD:main
          fi

      - name: Upload artifact (for quick download)
        uses: actions/upload-artifact@v4
        with:
          name: wtp-snapshot-${{ env.SITE_KEY }}
          path: |
            ${{ env.OUTDIR }}/**
          if-no-files-found: warn
          retention-days: 7
